### ISSUE TITLE
[BUG] 需要更新网页版抖音的解析方式

### ISSUE THREAD

**Issue by limitMe** [Johnserf-Seed/TikTokDownload#181]
**描述出现的错误**

```
python TikTokDownload.py

        使用方法: 1、添加为环境变量 2、输入命令
        -u<url 抖音复制的链接:https://v.douyin.com/JtcjTwo/>
        -m<music 是否下载音频,默认为yes可选no>

        例如：TikTokDownload.exe -u https://v.douyin.com/JtcjTwo/ -m yes

    
请输入抖音链接: https://v.douyin.com/2mv5xHN/
Traceback (most recent call last):
  File "TikTokDownload.py", line 114, in <module>
    video_download(urlarg,musicarg)
  File "TikTokDownload.py", line 89, in video_download
    key = re.findall('video/(\d+)?',str(r.url))[0]
IndexError: list index out of range
```

**bug复现**
复现这次行为的步骤：
1.更改了什么什么
2.点击了什么什么
3.“……”

**截图**
如果适用，添加屏幕截图以帮助解释您的问题。

**桌面（请填写以下信息）：**
-操作系统：[例如windows10 64bit]
-vpn代理[例如开启、关闭]
-版本[如1.2.3]

**附文**
解析出来的第一个链接现在是个跳转网页，无法从中直接解析vedio地址了。

**Comment by Johnserf-Seed** [comment]
为什么你把用户主页链接放单视频下载这里
要用批量下载
