### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by ohmerci** [Johnserf-Seed/TikTokDownload#245]
**描述出现的错误**
视频文案中带有撇号“ ’ ”的话会出现报错闪退

`Traceback (most recent call last):
  File "TikTokDownload\TikTokTool.py", line 29, in <module>
  File "TikTokDownload\Util\Profile.py", line 75, in getProfile
AttributeError: 'Profile' object has no attribute 'sec'
[28868] Failed to execute script TikTokTool`

**bug复现**
复现这次行为的步骤：
./tiktoktool -u https://v.douyin.com/rR7LxRF/

-操作系统：win 11 64

-版本1.3.0

**Comment by Johnserf-Seed** [comment]
tiktoktool只接受用户主页链接，不是程序问题

**Comment by ohmerci** [comment]
> tiktoktool只接受用户主页链接，不是程序问题

我使用时是填写的主页链接，只是这里放出了闪退的那个视频链接
