### ISSUE TITLE
TikTokTool.exe运行时出现异常

### ISSUE THREAD

**Issue by d930fc** [Johnserf-Seed/TikTokDownload#256]
conf.ini：
```
[uid]
uid = https://www.douyin.com/user/MS4wLjABAAAA8JAy1VPimfDkB-GULCkkzD0eXxc9BTvePuQZRQ4lXF8?vid=7153704250856574241

[music]
music = no

[mode]
mode = post
```
命令行：
```
D:\抖音\小王马>TikTokTool.exe
```
异常输出：
```
[  提示  ]: 2022-09-04 14.18.31华仔，你用冰雨疗好了多少笨小孩的伤 #刘德华演唱会 [文件已存在，为您跳过]
[  提示  ]: 2022-09-04 07.16.39四大发明到底是不是科学？ #四大发明 #科学 #工业革命 #文艺复兴 #中华文化 [文件已存在，为您跳过]
[  提示  ]: 2022-09-03 17.54.25同为论道，为什么赫拉克利特主张战争，而孔子却反对战争呢？ #赫拉克利特 #哲学 [文件已存在，为您跳过]
[  提示  ]: 2022-09-02 05.26.53为什么科学源于古希腊而不是中国呢？ #科学 #哲学 #古希腊 [文件已存在，为您跳过]
[  提示  ]: 2022-09-01 14.42.42延迟开学，又要上演手机之战 #开学 #玩手机 #学生玩手机 [文件已存在，为您跳过]
[  提示  ]: 2022-08-31 17.21.21中国古代有数学，为什么我们现却还学着西方数学呢？ #读书 #毕达哥拉斯 #柏拉图 #数学 #哲学 #古希腊 [文件已存在，为您跳过]
[  提示  ]: 2022-08-31 01.12.42贾浅浅，你以为真的在批判你的诗吗？#贾浅浅教授的诗  [文件已存在，为您跳过]
[  提示  ]: 2022-08-30 15.22.24贾浅浅，你的诗动了我们的底线？ #贾浅浅的诗 #知识分享  [文件已存在，为您跳过]
[  提示  ]: 2022-08-26 05.37.56为什么西方人很容易原谅名人的私生活？ #希腊神话 [文件已存在，为您跳过]
[  提示  ]: 2022-08-24 04.49.45如何评价胡锡进对教材问题的处理要注意区别犯错和犯罪？ #知识分享 [文件已存在，为您跳过]
[  提示  ]:正在对 1661287785000 页进行第 1 次尝试！
[  提示  ]:第 1654105712000 页抓获数据成功!
[  提示  ]:等待替换文案非法字符!
[  提示  ]:等待替换作者非法字符!
Traceback (most recent call last):
  File "TikTokDownload\TikTokTool.py", line 29, in <module>
  File "TikTokDownload\Util\Profile.py", line 106, in getProfile
  File "TikTokDownload\Util\Profile.py", line 151, in getData
  File "TikTokDownload\Util\Profile.py", line 254, in getVideoInfo
  File "TikTokDownload\Util\Profile.py", line 193, in getNextData
  File "TikTokDownload\Util\Profile.py", line 254, in getVideoInfo
  File "TikTokDownload\Util\Profile.py", line 193, in getNextData
  File "TikTokDownload\Util\Profile.py", line 254, in getVideoInfo
  File "TikTokDownload\Util\Profile.py", line 193, in getNextData
  File "TikTokDownload\Util\Profile.py", line 251, in getVideoInfo
  File "TikTokDownload\Util\Images.py", line 49, in get_all_images
TypeError: object of type 'NoneType' has no len()
[12756] Failed to execute script TikTokTool

D:\抖音\小王马>
```

**Comment by Johnserf-Seed** [comment]
感谢提issue，这是我没有测试到的情况，现已修复
