### ISSUE TITLE
[BUG]获取最新版本号失败导致程序报错

### ISSUE THREAD

**Issue by flyshu** [Johnserf-Seed/TikTokDownload#264]
**描述出现的错误**
获取最新版本号失败导致程序报错

**bug复现**
复现这次行为的步骤：
1.运行tiktoktool.exe程序
2.出现“获取最新版本号中!”
3.一段时间后报错“获取网络版本号失败!”

`Traceback (most recent call last):
  File "TikTokDownload\TikTokTool.py", line 17, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "E:\Program Files (x86)\Python\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 623, in exec_module
  File "TikTokDownload\Util\__init__.py", line 140, in <module>
  File "TikTokDownload\TikTokUpdata.py", line 63, in get_Updata
AttributeError: 'Updata' object has no attribute 'g_Version'
[6952] Failed to execute script TikTokTool`

**截图**
![image](https://user-images.githubusercontent.com/4252583/206113159-bc31ab2e-539f-4d1a-80e2-37889bd30542.png)

**桌面（请填写以下信息）：**
-操作系统：windows10 64bit
-vpn代理开启关闭都试过，都会闪退。
-版本1.3.0.33

**附文**
在此处添加有关此问题的文字。

**Comment by flyshu** [comment]
由于国内网络环境不好，建议加一个是否打开自动升级的开关或者参数，以便关闭每次下载前的升级检测

**Comment by Johnserf-Seed** [comment]
做了捕获错误的，获取失败也不影响后续运行

**Comment by Johnserf-Seed** [comment]
而且用的是cdn代理，国内速度不会很差

**Comment by Johnserf-Seed** [comment]
重新用```build.bat```打包一下再运行
