### ISSUE TITLE
单个下载和批量下载均报错

### ISSUE THREAD

**Issue by yfchen97** [Johnserf-Seed/TikTokDownload#278]
Traceback (most recent call last):
  File "TikTokTool.py", line 29, in <module>
    profile.getProfile(cmd.setting())
  File "/Users/yfchen/Desktop/code/TikTokDownload-main/Util/Profile.py", line 73, in getProfile
    post_name_json = Util.json.loads(Util.requests.get(url = post_url, headers=self.headers).content.decode())
  File "/Users/yfchen/opt/anaconda3/envs/py37/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/Users/yfchen/opt/anaconda3/envs/py37/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Users/yfchen/opt/anaconda3/envs/py37/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by Johnserf-Seed** [comment]
已经成功解决加密参数，等待下个版本更新

**Comment by deyimsf** [comment]
遇到了同样的问题，请问下个版本预计是什么时间，感谢
