### ISSUE TITLE
下载 打开 TikTokMultiGUI.exe 报错

### ISSUE THREAD

**Issue by liu-runsen** [Johnserf-Seed/TikTokDownload#289]
Traceback (most recent call last):
  File "TikTokMultiGUI.py", line 28, in <module>
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 499, in exec_module
  File "Util\__init__.py", line 160, in <module>
  File "TikTokUpdata.py", line 67, in get_Updata
RuntimeError: input(): lost sys.stdin

**Comment by HELLO-MYLIFE** [comment]
Traceback (most recent call last):
  File "TikTokMultiGUI.py", line 28, in <module>
    from Util.Resource import *
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 499, in exec_module
  File "Util\__init__.py", line 160, in <module>
    Updata().get_Updata()
  File "TikTokUpdata.py", line 67, in get_Updata
    isUpdata = input('[   🌋   ]:当前不是最新版本,需要升级吗? (y/n) :')
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: input(): lost sys.stdin

**Comment by Johnserf-Seed** [comment]
将```TikTokUpdate.py:62```的
```
    def get_Updata(self):
        if self.l_Version == self.g_Version:
            print('[   🚩   ]:目前 %i 版本已是最新' % self.l_Version)
            return
        elif self.l_Version < self.g_Version:
            isUpdata = input('[   🌋   ]:当前不是最新版本,需要升级吗? (y/n) :')
            if isUpdata == 'Y' or isUpdata == 'y':
                print('[   🚩   ]:正在为你下载 %i 版本中，升级前请确保关闭所有打开的项目文件' %
                        self.g_Version)
                self.zip_Download()
            if isUpdata == 'N' or isUpdata == 'n':
                print('[   🚩   ]:取消升级,旧版可能会出现没有修复的bug')
                return
            else:
                self.get_Updata()
```
修改成
```
    def get_Updata(self):
        if self.l_Version == self.g_Version:
            print('[   🚩   ]:目前 %i 版本已是最新' % self.l_Version)
            return
        elif self.l_Version < self.g_Version:
                self.zip_Download()
                return
```
