### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by xxnbyy** [Johnserf-Seed/TikTokDownload#301]
运行最新版 download时报错
Traceback (most recent call last):
  File "C:\Users\admin\Downloads\TikTokDownload-main\TikTokDownload.py", line 148, in <module>
    video_download(url, music, name)
  File "C:\Users\admin\Downloads\TikTokDownload-main\TikTokDownload.py", line 113, in video_download
    key = re.findall('video/(\d+)?', str(r.url))[0]
IndexError: list index out of range

**Comment by Johnserf-Seed** [comment]
你用的不是最新版
