### ISSUE TITLE
[BUG] 获取用户数据失败，正在重新获取

### ISSUE THREAD

**Issue by ahlblzk** [Johnserf-Seed/TikTokDownload#306]
**描述出现的错误**
试了很多次，换了多个用户主页链接 全都是一直返回【获取用户数据失败，正在重新获取】，是不是主页的api又失效了

**截图**
<img width="1000" alt="WX20230208-023338@2x" src="https://user-images.githubusercontent.com/7858842/217334929-7f6a1ef0-04df-40d5-abba-d3ba0a0f1b0d.png">
log日志只到获取用户的sec_id之后就没了
[2023-02-08 02:33:15,066] - Log.py] - INFO: Darwin
[2023-02-08 02:33:15,267] - Log.py] - INFO: [  提示  ]:为您下载多个视频!
[2023-02-08 02:33:15,268] - Log.py] - INFO: [  提示  ]:用户的sec_id=MS4wLjABAAAAYmnPF3iPEIIjr-esv0yrrbAaczHl459LinsM25dq0iE

**桌面（请填写以下信息）：**
-操作系统：[mac Intel 64bit]
-vpn代理[关闭]
-版本[1.3.0.46]

**Comment by harryleo2022** [comment]
同样的问题

**Comment by harryleo2022** [comment]
然后py运行代码就是缺少ModuleNotFoundError: No module named 'lxml'

**Comment by harryleo2022** [comment]
Traceback (most recent call last):
  File "E:\抖音下载资料\TikTokDownload.py", line 148, in <module>
    video_download(url, music, name)
  File "E:\抖音下载资料\TikTokDownload.py", line 113, in video_download
    key = re.findall('video/(\d+)?', str(r.url))[0]
IndexError: list index out of range

**Comment by ahlblzk** [comment]
> 然后py运行代码就是缺少ModuleNotFoundError: No module named 'lxml'

你这个是依赖没安装啊 手动安装一下lxml

**Comment by harryleo2022** [comment]
这个装了，现在就是一直查询用户，神秘不了了！




请注意查收！

---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年2月8日(周三) 下午5:31
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Johnserf-Seed/TikTokDownload] [BUG] 获取用户数据失败，正在重新获取 (Issue #306)




  
然后py运行代码就是缺少ModuleNotFoundError: No module named 'lxml'
  
你这个是依赖没安装啊 手动安装一下lxml

**Comment by Johnserf-Seed** [comment]
接口挂了，换加密接口 稍安勿躁等待更新

**Comment by Johnserf-Seed** [comment]
重新运行获取1.3.0.50版本更新

**Comment by harryleo2022** [comment]
运行更新就闪退，重新下载了运营也闪退

**Comment by Johnserf-Seed** [comment]
> 运行更新就闪退，重新下载了运营也闪退

闪退是我找的加速github下载的服务器挂了，直接从仓库的release下载吧

**Comment by Johnserf-Seed** [comment]
![image](https://user-images.githubusercontent.com/40727745/217770782-94c53914-fd8a-4567-9c46-57879e2e5d70.png)

**Comment by Johnserf-Seed** [comment]
> 大佬，弱弱问一句，您说的仓库是哪里？不是这个网站吗？🥺🥺🥺
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2023年2月9日(周四) 下午5:19 收件人: ***@***.***&gt;; 抄送: ***@***.******@***.***&gt;; 主题: Re: [Johnserf-Seed/TikTokDownload] [BUG] 获取用户数据失败，正在重新获取 (Issue #306) 运行更新就闪退，重新下载了运营也闪退 闪退是我找的加速github下载的服务器挂了，直接从仓库的release下载吧 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;

因为国内访问github速度的缘故，下载release和archive一般都失败，所以采用的https://github.com/hunshcn/gh-proxy 仓库的下载加速站，但是这个站现在流量太大炸了

**Comment by Johnserf-Seed** [comment]
现在切换回官方下载地址了，也可以自行找下载镜像来修改TikTokUpdate.py里的下载地址
https://github.com/Johnserf-Seed/TikTokDownload/commit/ef0edccbcf1d8926da03ad2984eb907eefeab320
