### ISSUE TITLE
遇到的问题和开发者更新说明贴

### ISSUE THREAD

**Issue by Johnserf-Seed** [Johnserf-Seed/TikTokDownload#311]
# 关于此贴
此贴用于更新一些**开发说明**，和**遇到的故障**解决以及**列出详细的问题**和**提问交流**

## 关于终端
我用的是Windows Terminal  <a href="https://aka.ms/terminal" data-linktype="external" class="button button-primary button-filled has-text-wrap">安装 Windows 终端</a>
![image](https://user-images.githubusercontent.com/40727745/217790509-4a4c6318-c787-449d-a4ee-55d8395b4f81.png)

## 关于No module named 'xxx'
在项目文件夹空白处中按shift + 鼠标右键  选择在终端中打开 或 在此处打开xxx shell
输入 ```pip install -r requirements.txt``` 安装项目依赖
如有其他依赖报错在此贴下回复

## 关于更新
最近抖音更新非常频繁，所以本项目也在频繁更新。 
**Q：为什么用了更新的版本还是无法运行？**
A：更新完之后exe需要同步打包才能应用更新或者和我更新的代码存在差异。

为了保证大家用的代码和我开发环境一致，[Release](https://github.com/Johnserf-Seed/TikTokDownload/releases/) 页面提供了最新打包好的exe文件的md5。
每次在```TikTokTool```中更新完之后用```build.bat```重新打包文件，或者直接使用py运行，才是最新可运行的版本。

## 关于网络
![image](https://user-images.githubusercontent.com/40727745/217784034-4e6510a6-3e0e-4174-a5e1-36d9b90c0023.png)

**Q：为什么我用了代理还是出现网络不太通畅？**
A：可能是github自己抽风，可以检查本地dns有无污染，向host文件填写代理ip后重置电脑网络缓存 ```ipconfig /flushdns``` 后再试。

推荐没有代理的人使用[羽翼城](https://www.dogfight360.com/)大佬的工具 [steamcommunity_302](https://www.dogfight360.com/blog/686/)
![image](https://user-images.githubusercontent.com/40727745/217785230-b55fd64b-ac9f-47c5-bb4a-3b36e3640f95.png)

## 日志
+ 更新包地址切换回官方 https://github.com/Johnserf-Seed/TikTokDownload/archive/master.zip
+ 配置文件新增几大功能 (后续更新)
+ <img src="https://user-images.githubusercontent.com/40727745/217791894-f97cbec9-77de-4a0f-a192-36084ecec0e0.png" alt="image" width="700" data-width="500">

## 镜像加速站替换更新链接
- https://gh.api.99988866.xyz/ (旧用，暂挂)
- https://g.ioiox.com/ (已挂)
- https://github.welab.eu.org/ (未测)
- https://tool.mintimate.cn/gh/ (未测)
- https://pd.zwc365.com/ (未测)

更新于 2023/02/09 18:58

**Comment by navyNIE** [comment]
![微信图片_20230212153148](https://user-images.githubusercontent.com/39463704/218299146-ebffd24f-c6b6-437b-82ac-f561132063b1.png)
您好，我安装了requirements里的依赖库，下载的时候还是碰到no module named的问题

**Comment by skyhhuc** [comment]
你好，请问我直接用pycharm运行你们tiktoktool.py，并且所有步骤都按照你上面的来，环境和node.js都安装了，但是一直报错Profile对象没有sec属性，请看截图，麻烦帮我指点一下是哪里出了问题，感谢![230982440-d802f2b1-c7f3-4430-8499-960e77e99f6d.png](https://user-images.githubusercontent.com/66587321/231287674-8a38d9c9-8fce-4426-b883-70f2c210a037.png)

**Comment by skyhhuc** [comment]
https://www.tiktok.com/@cocosneaker0
这个是我设置的链接，然后cookie就按照conf.ini提示的那三个字段也都通过f12找到并填上去了。但是还是有那个问题，sec没有这个属性

**Comment by namedssy** [comment]
> https://www.tiktok.com/@cocosneaker0 这个是我设置的链接，然后cookie就按照conf.ini提示的那三个字段也都通过f12找到并填上去了。但是还是有那个问题，sec没有这个属性

有解决吗  我也遇到这个问题了  是不是不能下载 tiktok 的视频？

**Comment by skyhhuc** [comment]
> > https://www.tiktok.com/@cocosneaker0 这个是我设置的链接，然后cookie就按照conf.ini提示的那三个字段也都通过f12找到并填上去了。但是还是有那个问题，sec没有这个属性
> 
> 有解决吗  我也遇到这个问题了  是不是不能下载 tiktok 的视频？

要看中文。。。只是抖音而已，没有tiktok😂😂😂

**Comment by fungchunhoeasy** [comment]
Traceback (most recent call last):
File "F:\抖音视频下载\TikTokTool.py", line 32, in
profile.getProfile(cmd.setting())
File "F:\抖音视频下载\Util\Profile.py", line 84, in getProfile
datas = Util.XBogus('aid=6383&sec_user_id=%s&count=35&max_cursor=0&cookie_enabled=true&platform=PC&downlink=10' % (
File "F:\抖音视频下载\Util\XB.py", line 30, in init
self.getXbogus(url)
File "F:\抖音视频下载\Util\XB.py", line 50, in getXbogus
self.params = response["result"][0]["paramsencode"]
UnboundLocalError: cannot access local variable 'response' where it is not associated with a value

请问各位大神要怎么解决？
跪求！！！！ 已经先运行server.bat

**Comment by maxchiron** [comment]
Seed大大，请问现在-u参数是失效了吗？uid放conf.ini里可以正常下载，用-u的话，就会提示“获取用户数据失败，请从web端获取新ttwid填入配置文件”报错

**Comment by zhangzongwan** [comment]
<img width="1202" alt="image" src="https://github.com/Johnserf-Seed/TikTokDownload/assets/59790659/d0baa340-bbf6-412b-b951-e62a7f45b807">
卡在[  提示  ]:用户的sec_id=MS4wLjABAAAA2dvvSlRH9phwjH21auoTpQ7bg_cCeRQhLe34EYN8gW8，无法下载

**Comment by keeper-jie** [comment]
是否不支持bilibili视频下载，我安装f2框架之后使用`f2 bili -h`显示未安装此模块，下载源码之后`pip install -r requirement.txt`之后还是显示未安装此模块，是否不支持bilibili视频爬取？

**Comment by Johnserf-Seed** [comment]
> 是否不支持bilibili视频下载，我安装f2框架之后使用`f2 bili -h`显示未安装此模块，下载源码之后`pip install -r requirement.txt`之后还是显示未安装此模块，是否不支持bilibili视频爬取？ @Johnserf-Seed 
> 
> ```
> (tiktokdownload) D:\file\file\Win10Share\md\python\code\MediaCrawler\tiktokdownload\TikTokDownload-main>f2 bili -h
> ERROR    Error: No module named 'f2.apps.bilibili'
> Usage: f2 [OPTIONS] COMMAND [ARGS]...
> 
> Error: No such command 'bili'.
> ```
> 而`f2 dy -h`是正常的
> 
> 我查看了site-package中的f2源码，只有tiktok和douyin，可否在`f2 -h`中删去其它选项呢，我理解未实现的功能就不用放help中了，避免使用者浪费时间做无用功

readme和help的应用支持状态写的很清楚，这个这是告诉用户未来支持的平台，不知道有这么难理解吗？

**Comment by keeper-jie** [comment]
> > 是否不支持bilibili视频下载，我安装f2框架之后使用`f2 bili -h`显示未安装此模块，下载源码之后`pip install -r requirement.txt`之后还是显示未安装此模块，是否不支持bilibili视频爬取？ @Johnserf-Seed
> > ```
> > (tiktokdownload) D:\file\file\Win10Share\md\python\code\MediaCrawler\tiktokdownload\TikTokDownload-main>f2 bili -h
> > ERROR    Error: No module named 'f2.apps.bilibili'
> > Usage: f2 [OPTIONS] COMMAND [ARGS]...
> > 
> > Error: No such command 'bili'.
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 而`f2 dy -h`是正常的
> > 我查看了site-package中的f2源码，只有tiktok和douyin，可否在`f2 -h`中删去其它选项呢，我理解未实现的功能就不用放help中了，避免使用者浪费时间做无用功
> 
> readme和help的应用支持状态写的很清楚，这个这是告诉用户未来支持的平台，不知道有这么难理解吗？

抱歉是我的问题，我认为help里面应该放已有的功能指令，readme放计划的feature，比如linux中的ls命令，不会help里面放没有实现的东西
