### ISSUE TITLE
[BUG]TikTokLive失效.JSONDecodeError

### ISSUE THREAD

**Issue by boluohong** [Johnserf-Seed/TikTokDownload#314]
TikTokLive失效
已测试多个账户
均提示.JSONDecodeError

具体如下

[   💻   ]:Windows平台
[   🗻   ]:获取最新版本号中!
[   🚩   ]:目前 13050 版本已是最新
[   📺   ]:输入抖音直播间web端链接，例如 https://live.douyin.com/176819813905：h
ttps://live.douyin.com/40202968686
Traceback (most recent call last):
  File "D:\20230209\TikTokLive.py", line 22, in <module>
    json = Util.Lives.get_Live(live_url)
  File "D:\20230209\Util\Lives.py", line 35, in get_Live
    live_json = Util.json.loads(response.text)
  File "C:\Users\hp\AppData\Local\Programs\Python\Python37\lib\json\__init__.py"
, line 348, in loads
    return _default_decoder.decode(s)
  File "C:\Users\hp\AppData\Local\Programs\Python\Python37\lib\json\decoder.py",
 line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\hp\AppData\Local\Programs\Python\Python37\lib\json\decoder.py",
 line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by zzh151223** [comment]
referer改为https://www.douyin.com/user/MS4wLjABAAAAKSLE7lI1UVdQ23V768LVwRuf84KfZI3ZYUXslDnjJ_c，目前使用任意一个用户的主页都可以

**Comment by NormanMises** [comment]
目前已经失效不能用了

**Comment by Johnserf-Seed** [comment]
可以用 自己先改源码 我等更新新功能在一并推送

**Comment by Johnserf-Seed** [comment]
live加上xg就好了
