### ISSUE TITLE
[BUG]UnboundLocalError:cannot access local variable 'response' where it is not associated with a value

### ISSUE THREAD

**Issue by ahlblzk** [Johnserf-Seed/TikTokDownload#316]
**描述出现的错误**
命令行运行：python TikTokPic.py 

[  错误  ]:Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "/Users/lzk/Documents/Github/TikTokDownload/TikTokPic.py", line 211, in <module>
    pic_download(urlarg)
  File "/Users/lzk/Documents/Github/TikTokDownload/TikTokPic.py", line 165, in pic_download
    jx_url = Urls().POST_DETAIL + XBogus(
                                  ^^^^^^^
  File "/Users/lzk/Documents/Github/TikTokDownload/Util/XB.py", line 30, in __init__
    self.getXbogus(url)
  File "/Users/lzk/Documents/Github/TikTokDownload/Util/XB.py", line 50, in getXbogus
    self.params = response["result"][0]["paramsencode"]
                  ^^^^^^^^
UnboundLocalError: cannot access local variable 'response' where it is not associated with a value

**截图**
<img width="831" alt="WX20230211-011229@2x" src="https://user-images.githubusercontent.com/7858842/218153941-d21ce282-4efd-495c-905a-50db9c590cad.png">

**附文**
另外运行编译后的TikTokPic也是一样的，报错如下：
[  错误  ]:Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "TikTokPic.py", line 211, in <module>
  File "TikTokPic.py", line 165, in pic_download
  File "Util/XB.py", line 30, in __init__
  File "Util/XB.py", line 50, in getXbogus
UnboundLocalError: local variable 'response' referenced before assignment
[45285] Failed to execute script 'TikTokPic' due to unhandled exception!

**Comment by Johnserf-Seed** [comment]
现在切换接口了，重新pull一下

**Comment by ahlblzk** [comment]
> 现在切换接口了，重新pull一下

兄弟太晚了 注意休息

接口应该可以了，视频下载没问题，图文下载之后的图片提示文件已损坏
我是mac系统
![Uploading WX20230211-025203@2x.png…]()
![Uploading image.png…]()

**Comment by ahlblzk** [comment]
> 现在切换接口了，重新pull一下

兄弟太晚了 注意休息

接口应该可以了，视频下载没问题，图文下载之后的图片提示文件已损坏
我是mac系统
![Uploading WX20230211-025203@2x.png…]()
![Uploading image.png…]()

**Comment by ahlblzk** [comment]
> 现在切换接口了，重新pull一下

刚才又跑了下程序，TikTokTool批量下载的图文是ok的，TikTokPic下载的图文是已损坏的

**Comment by xx254** [comment]
我依然有这个问题, 用的是最新的 code, 请问最后是怎么解决的呀
