### ISSUE TITLE
运行似乎不稳定[BUG]

### ISSUE THREAD

**Issue by zzylmt** [Johnserf-Seed/TikTokDownload#317]
[  错误  ]:Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "c:\Users\DELL\Desktop\TikTokDownload\TikTokDownload.py", line 152, in <module>
    video_download(url, music, name)
  File "c:\Users\DELL\Desktop\TikTokDownload\TikTokDownload.py", line 122, in video_download
    jx_url = Util.Urls().POST_DETAIL + Util.XBogus(
                                       ^^^^^^^^^^^^
  File "c:\Users\DELL\Desktop\TikTokDownload\Util\XB.py", line 30, in __init__
    self.getXbogus(url)
  File "c:\Users\DELL\Desktop\TikTokDownload\Util\XB.py", line 50, in getXbogus
    self.params = response["result"][0]["paramsencode"]
                  ^^^^^^^^
UnboundLocalError: cannot access local variable 'response' where it is not associated with a value

最新版运行有时会报以上错误。似乎是随机出现。当我不做任何修改，关闭IDE，重新运行，又可以正常下载。
难道是网络获取某些参数时会有缺失？

**Comment by Johnserf-Seed** [comment]
服务器阈值是20并发，可能某些时间段比较拥挤

**Comment by Johnserf-Seed** [comment]
![image](https://user-images.githubusercontent.com/40727745/218251179-4b92419c-4cc1-43f8-abbd-c3e27c82d5d6.png)
现在调节了
