### ISSUE TITLE
[BUG]获取用户数据失败，请从web端获取新ttwid

### ISSUE THREAD

**Issue by doio** [Johnserf-Seed/TikTokDownload#335]
**描述出现的错误**
【注意】获取用户数据失败，请从web端获取新ttwid

**bug复现**
复现这次行为的步骤：
复制了抖音链接到 conf 里面，执行 TikTokTool.exe

**截图**
如果适用，添加屏幕截图以帮助解释您的问题。

**桌面（请填写以下信息）：**
-操作系统：Windows 11 64-bit
-vpn代理[例如开启、关闭]
-版本 v1.3.0.54

**附文**
下载一个用户的图文和视频出现这个

![Uploading 2023-03-02_20-44-44.jpg…]()

**Comment by zhiben5201** [comment]
刚好也就是刚才，我也发现这个问题，而且无法通过重启路由器等方式自行修复

**Comment by eightrivers** [comment]
同样的问题出现+1

大概8个小时前还是正常的~

**Comment by boluohong** [comment]
2023-03-03 09：03亲测解决

只需要把cookie里的所有内容都填进去就可以

**Comment by zhiben5201** [comment]
> 

折腾了半天还是不会弄啊，我是EDGE浏览器，找不到你说的那个COOKIE的地方，往上自己搜索方法出来的东西不知道该怎么复制
![1677813539774](https://user-images.githubusercontent.com/103325310/222622944-0a0e79ed-bcd3-4d2a-b776-d8c5b665f4bb.png)

**Comment by Hsirehc** [comment]
> 2023-03-03 09：03亲测解决
> 
> 以前只需要ttwid,昨天更新后是增加了其他的密钥验证 只需要把cookie里的所有内容都填进去就可以
> 
> 【如何更改】 1.获得cookie （1）在电脑浏览器中打开任意抖音主页 （2）按F12---->点击network选项卡--->点击doc选项 （3）再在左下角name选项卡中任选一项---->Headerr--->RequestHeaders--->cookie （4）复制cookie里的内容 如果仍然不会，请谷歌“如何查看网页cookies”
> 
> 2.将获得的cookie填在__init__.py （1）打开本项目文件夹 （2）打开Util文件夹 （3）打开文件__init__.py
> 
> 将新获得的cookie【补充】进旧的cookie 注意是【补充】 要保留【f'msToken={generate_random_str(107)};】字段 形如： 'Cookie': f'msToken={generate_random_str(107)};ttwid=...............................}

获取作品信息返回还是为空

**Comment by zhiben5201** [comment]
> 标题器

没有COOKIES的选项
![1677815039933](https://user-images.githubusercontent.com/103325310/222626246-99188c89-92ad-41a1-80b5-4c5727f2671a.png)

**Comment by eightrivers** [comment]
> > 2023-03-03 09：03亲测解决
> > 以前只需要ttwid,昨天更新后是增加了其他的密钥验证 只需要把cookie里的所有内容都填进去就可以
> > 【如何更改】 1.获得cookie （1）在电脑浏览器中打开任意抖音主页 （2）按F12---->点击network选项卡--->点击doc选项 （3）再在左下角name选项卡中任选一项---->Headerr--->RequestHeaders--->cookie （4）复制cookie里的内容 如果仍然不会，请谷歌“如何查看网页cookies”
> > 2.将获得的cookie填在__init__.py （1）打开本项目文件夹 （2）打开Util文件夹 （3）打开文件__init__.py
> > 将新获得的cookie【补充】进旧的cookie 注意是【补充】 要保留【f'msToken={generate_random_str(107)};】字段 形如： 'Cookie': f'msToken={generate_random_str(107)};ttwid=...............................}
> 
> 获取作品信息返回还是为空

以上的这个帖子被删除掉了么？

**Comment by zhiben5201** [comment]
> > > 2023-03-03 09：03亲测解决
> > > 以前只需要ttwid,昨天更新后是增加了其他的密钥验证 只需要把cookie里的所有内容都填进去就可以
> > > 【如何更改】 1.获得cookie （1）在电脑浏览器中打开任意抖音主页 （2）按F12---->点击network选项卡--->点击doc选项 （3）再在左下角name选项卡中任选一项---->Headerr--->RequestHeaders--->cookie （4）复制cookie里的内容 如果仍然不会，请谷歌“如何查看网页cookies”
> > > 2.将获得的cookie填在__init__.py （1）打开本项目文件夹 （2）打开Util文件夹 （3）打开文件__init__.py
> > > 将新获得的cookie【补充】进旧的cookie 注意是【补充】 要保留【f'msToken={generate_random_str(107)};】字段 形如： 'Cookie': f'msToken={generate_random_str(107)};ttwid=...............................}
> > 
> > 
> > 获取作品信息返回还是为空
> 
> 以上的这个帖子被删除掉了么？

我尝试了半天是不行的，估计是发帖者自己删了吧

**Comment by eightrivers** [comment]
> > > > 2023-03-03 09：03亲测解决
> > > > 以前只需要ttwid,昨天更新后是增加了其他的密钥验证 只需要把cookie里的所有内容都填进去就可以
> > > > 【如何更改】 1.获得cookie （1）在电脑浏览器中打开任意抖音主页 （2）按F12---->点击network选项卡--->点击doc选项 （3）再在左下角name选项卡中任选一项---->Headerr--->RequestHeaders--->cookie （4）复制cookie里的内容 如果仍然不会，请谷歌“如何查看网页cookies”
> > > > 2.将获得的cookie填在__init__.py （1）打开本项目文件夹 （2）打开Util文件夹 （3）打开文件__init__.py
> > > > 将新获得的cookie【补充】进旧的cookie 注意是【补充】 要保留【f'msToken={generate_random_str(107)};】字段 形如： 'Cookie': f'msToken={generate_random_str(107)};ttwid=...............................}
> > > 
> > > 
> > > 获取作品信息返回还是为空
> > 
> > 
> > 以上的这个帖子被删除掉了么？
> 
> 我尝试了半天是不行的，估计是发帖者自己删了吧

好吧，坐等大佬更新~ 

先抱拳谢过！

**Comment by Vinsea** [comment]
@doio @zhiben5201 @eightrivers 。我这解决了。不能用`exe`，得直接用python执行脚本
就是把cookie的值全部覆盖`__init__.py`里对应的值就行。可能抖音官方新加了什么header校验吧

**Comment by zhiben5201** [comment]
> @doio @zhiben5201 @eightrivers 。我这解决了。不能用`exe`，得直接用python执行脚本 就是把cookie的值全部覆盖`__init__.py`里对应的值就行。可能抖音官方新加了什么header校验吧

谢谢，我完全没有编码这方面知识储备，根本看不懂，白天找COOKIE都找了半天，目前也只能等作者更新了

**Comment by Johnserf-Seed** [comment]
都写了是自行替换，就是我更新了cookie还是会失效的  自行替换打包

**Comment by Vinsea** [comment]
> 都写了是自行替换，就是我更新了cookie还是会失效的 自行替换打包

@Johnserf-Seed 我排查发现在原来基础上加上 sid_guard 这个字段就好了，但不知道这个字段干啥用的

**Comment by zhiben5201** [comment]
> 都写了是自行替换，就是我更新了cookie还是会失效的 自行替换打包

具体怎么操作啊，我没有一点编码知识，找到了COOKIES，尝试了各种复制编辑__init__.py的方法都没用

**Comment by eightrivers** [comment]
> 

照抄这段，亲测有效
![微信截图_20230304125845](https://user-images.githubusercontent.com/1868294/222876810-4e1cfe36-00f0-4c31-997c-a839d8664543.png)

**Comment by zhiben5201** [comment]
> > 
> 
> 照抄这段，亲测有效 ![微信截图_20230304125845](https://user-images.githubusercontent.com/1868294/222876810-4e1cfe36-00f0-4c31-997c-a839d8664543.png)

谢谢，这个抄到哪里？

**Comment by zhiben5201** [comment]
> > 
> 
> 照抄这段，亲测有效 ![微信截图_20230304125845](https://user-images.githubusercontent.com/1868294/222876810-4e1cfe36-00f0-4c31-997c-a839d8664543.png)

![1677913339562](https://user-images.githubusercontent.com/103325310/222881222-910efcf7-4606-4049-a1f1-d1cd00d66ac5.png)
这样改对吗，数据是我自己浏览器找到的

**Comment by eightrivers** [comment]
> > > 
> > 
> > 
> > 照抄这段，亲测有效 ![微信截图_20230304125845](https://user-images.githubusercontent.com/1868294/222876810-4e1cfe36-00f0-4c31-997c-a839d8664543.png)
> 
> ![1677913339562](https://user-images.githubusercontent.com/103325310/222881222-910efcf7-4606-4049-a1f1-d1cd00d66ac5.png) 这样改对吗，数据是我自己浏览器找到的

看起来你可能没有python的运行环境，可能这样改了也不好使~~ 

捯饬这个最好还是需要有一些编程基础，要不就等大神改完后打包成exe，你直接执行就好了

**Comment by eightrivers** [comment]
亲测只需要添加一个新的cookie就好了，名字是：passport_csrf_token，当前有效值为：'7492ca4093c9c7266e9593af38731059'

**Comment by zhiben5201** [comment]
> 亲测只需要添加一个新的cookie就好了，名字是：passport_csrf_token，当前有效值为：'7492ca4093c9c7266e9593af38731059'

我确实没有一点编程基础，从小就只对文科感兴趣，电脑也了解个皮毛，照猫画虎可以，但这个确实不行

**Comment by eightrivers** [comment]
> > 亲测只需要添加一个新的cookie就好了，名字是：passport_csrf_token，当前有效值为：'7492ca4093c9c7266e9593af38731059'
> 
> 我确实没有一点编程基础，从小就只对文科感兴趣，电脑也了解个皮毛，照猫画虎可以，但这个确实不行

文科同学能注册github账号讨论技术问题，也是蛮让人敬佩的，加油！

**Comment by zhiben5201** [comment]
> > > 亲测只需要添加一个新的cookie就好了，名字是：passport_csrf_token，当前有效值为：'7492ca4093c9c7266e9593af38731059'
> > 
> > 
> > 我确实没有一点编程基础，从小就只对文科感兴趣，电脑也了解个皮毛，照猫画虎可以，但这个确实不行
> 
> 文科同学能注册github账号讨论技术问题，也是蛮让人敬佩的，加油！

我本身以为自己的电脑水平不错了，而且也非常喜欢研究，但这次这个问题上我确实感觉不行了，前面各位大神的回复每个字我都认识，但就是不明白是什么意思，可能这次我不得不放弃躺平了

**Comment by Johnserf-Seed** [comment]
等我晚点更新，又研究出来odin_tt的生成了，下个版本把cookie放配置文件读，就不需要这么麻烦一次一次改了

**Comment by harryleo2022** [comment]
> 等我晚点更新，又研究出来odin_tt的生成了，下个版本把cookie放配置文件读，就不需要这么麻烦一次一次改了

太nice了，小白坐等大佬更新了

**Comment by mr-lz** [comment]
> 亲测只需要添加一个新的cookie就好了，名字是：passport_csrf_token，当前有效值为：'7492ca4093c9c7266e9593af38731059'

亲测有效。
具体步骤：
项目目录 → `Util`目录  → `__init__.py`
![图片](https://user-images.githubusercontent.com/23637040/222956644-f7563dbe-7cd9-44dc-8f9a-bdc9cb1e2a4e.png)

**Comment by zhiben5201** [comment]
> > 亲测只需要添加一个新的cookie就好了，名字是：passport_csrf_token，当前有效值为：'7492ca4093c9c7266e9593af38731059'
> 
> 亲测有效。 具体步骤： 项目目录 → `Util`目录 → `__init__.py` ![图片](https://user-images.githubusercontent.com/23637040/222956644-f7563dbe-7cd9-44dc-8f9a-bdc9cb1e2a4e.png)

试了一下，如果只是修改这个文本的话，我这边还是无效的

**Comment by mr-lz** [comment]
> > > 亲测只需要添加一个新的cookie就好了，名字是：passport_csrf_token，当前有效值为：'7492ca4093c9c7266e9593af38731059'
> > 
> > 
> > 亲测有效。 具体步骤： 项目目录 → `Util`目录 → `__init__.py` ![图片](https://user-images.githubusercontent.com/23637040/222956644-f7563dbe-7cd9-44dc-8f9a-bdc9cb1e2a4e.png)
> 
> 试了一下，如果只是修改这个文本的话，我这边还是无效的 ![1678023668909](https://user-images.githubusercontent.com/103325310/222964032-84171570-397f-455c-921e-fd92f4824216.jpg)

我是`python TikTokTool.py`，直接用`TikTokTool.exe`还是会报错。

**Comment by cmpunk160** [comment]
> > > > 亲测只需要添加一个新的cookie就好了，名字是：passport_csrf_token，当前有效值为：'7492ca4093c9c7266e9593af38731059'
> > > 
> > > 
> > > 亲测有效。 具体步骤： 项目目录 → `Util`目录 → `__init__.py` ![图片](https://user-images.githubusercontent.com/23637040/222956644-f7563dbe-7cd9-44dc-8f9a-bdc9cb1e2a4e.png)
> > 
> > 
> > 试了一下，如果只是修改这个文本的话，我这边还是无效的 ![1678023668909](https://user-images.githubusercontent.com/103325310/222964032-84171570-397f-455c-921e-fd92f4824216.jpg)
> 
> 我是`python TikTokTool.py`，直接用`TikTokTool.exe`还是会报错。

尝试了一下在IDLE中修改运行py文件确实可以，但下载速度极慢，感觉不是网络问题

**Comment by moexizer** [comment]
我直接用 headers 里的 cookies 把 f' ' 之间的内容一股脑替换，然后就正常运行下载了。

**Comment by 656696888** [comment]
全部替换真的可以了

**Comment by zhiben5201** [comment]
> 我直接用 headers 里的 cookies 把 f' ' 之间的内容一股脑替换，然后就正常运行下载了。

这个方法不用自己手动编辑只需要复制粘贴就可以了吗

**Comment by ismakegame** [comment]
请输入抖音链接:https://www.douyin.com/user/MS4wLjABAAAAO4r0HtGsT6phVBHgGwrRAZmEEoNoOMbinibaPmIkc38
Traceback (most recent call last):
  File "E:\tools\tiktokdownload\TikTokDownload.py", line 168, in <module>
    video_download(url, music, name)
  File "E:\tools\tiktokdownload\TikTokDownload.py", line 126, in video_download
    key = re.findall('video/(\d+)?', str(r.url))[0]
IndexError: list index out of range
PS E:\tools\tiktokdownload>
到这步报错了

**Comment by liy010** [comment]
> 请输入抖音链接:https://www.douyin.com/user/MS4wLjABAAAAO4r0HtGsT6phVBHgGwrRAZmEEoNoOMbinibaPmIkc38 Traceback (most recent call last): File "E:\tools\tiktokdownload\TikTokDownload.py", line 168, in video_download(url, music, name) File "E:\tools\tiktokdownload\TikTokDownload.py", line 126, in video_download key = re.findall('video/(\d+)?', str(r.url))[0] IndexError: list index out of range PS E:\tools\tiktokdownload> 到这步报错了

你用错了，这个程序是下载单条视频的，你输入的是用户主页的链接肯定爬取不到

**Comment by zjplab** [comment]
Cookie 这个76行改成这样:
```Python
'Cookie': f'msToken={generate_random_str(107)};ttwid={generate_ttwid()};odin_tt={odin_tt}; passport_csrf_token={generate_random_str(32)}; passport_csrf_token_default={generate_random_str(32)};'
```

**Comment by Hsirehc** [comment]
> Cookie 这个76行改成这样:
> 
> ```python
> 'Cookie': f'msToken={generate_random_str(107)};ttwid={generate_ttwid()};odin_tt={odin_tt}; passport_csrf_token={generate_random_str(32)}; passport_csrf_token_default={generate_random_str(32)};'
> ```

兄弟牛批

**Comment by zhiben5201** [comment]
> 

卧槽真的好了，太感谢了

**Comment by zhiben5201** [comment]
> Cookie 这个76行改成这样:
> 
> ```python
> 'Cookie': f'msToken={generate_random_str(107)};ttwid={generate_ttwid()};odin_tt={odin_tt}; passport_csrf_token={generate_random_str(32)}; passport_csrf_token_default={generate_random_str(32)};'
> ```

卧槽，真的好了，太感谢了

**Comment by chenkongming** [comment]
> Cookie 这个76行改成这样:
> 
> ```python
> 'Cookie': f'msToken={generate_random_str(107)};ttwid={generate_ttwid()};odin_tt={odin_tt}; passport_csrf_token={generate_random_str(32)}; passport_csrf_token_default={generate_random_str(32)};'
> ```

我赞

**Comment by Johnserf-Seed** [comment]
![image](https://user-images.githubusercontent.com/40727745/224260994-22448c3a-a885-49ca-a180-4534bc76b588.png)
![image](https://user-images.githubusercontent.com/40727745/224261410-42f08930-13c8-43cc-8f06-68de7c8b3e93.png)
新版本等下推送

**Comment by Johnserf-Seed** [comment]
> > 
> 
> 期待odin_tt的生成算法

odin_tt生成是app端的接口，方法是先请求注册设备获取设备id，再用设备id请求abtest接口。在返回的set-cookie中就有odin_tt参数了，比较麻烦所以直接在网页的cookie里拿吧

**Comment by Johnserf-Seed** [comment]
这次的更新大家会用吗，先开启server，然后把cookie填配置文件就可以批量下载了

**Comment by doio** [comment]
> 这次的更新大家会用吗，先开启server，然后把cookie填配置文件就可以批量下载了

会用了，哇， PS 界面现在好炫酷！！

作者牛逼！！

![2023-03-10_23-04-29](https://user-images.githubusercontent.com/4461202/224350855-a1ff4828-1c6d-406a-ad86-10f4af9f8a98.png)

**Comment by FredYuuu** [comment]
从前天下午开始最近版本用户主页数据返回内容为空了，手动替换cookie依然无法解决

**Comment by GH-XING** [comment]
1.3.0.80版本，这版本还是出现“获取用户数据失败，请从web端获取新ttwid填入配置文件”这个问题，请求各位大佬帮忙解决，谢谢。
