### ISSUE TITLE
[BUG] 使用TikTokTool进行用户视频和图集提取时，Images.py中的函数无法返回正确内容

### ISSUE THREAD

**Issue by Yuhyeong** [Johnserf-Seed/TikTokDownload#357]
获取主页的35个aweme_id后，开始下载
首先在下载图集的过程中出现了发送GET后返回的数据中无法提取text，即返回信息不正确的情况
`    def get_all_images(self, aweme_id):
        datas = []
        for id in aweme_id:
            jx_url = Util.Urls().POST_DETAIL + Util.XBogus(
                    f'aweme_id={id}&aid=1128&version_name=23.5.0&device_platform=android&os_version=2333').params

            r = Util.requests.get(url=jx_url, headers=self.headers).text
            js = Util.json.loads(r)

            self.nickname = js['aweme_detail']['author']['nickname']
            self.nickname = Util.replaceT(self.nickname)
            self.desc = js['aweme_detail']['desc']
            self.create_time = js['aweme_detail']['create_time']
            self.number = len(js['aweme_detail']['images'])`

在这个函数中对jx_url请求，返回的内容无效
且主页的aweme_id提取成功

**bug复现**

**截图**
Traceback (most recent call last):
  File "D:\TOOL\TikTokDownload\TikTokTool.py", line 32, in <module>
    profile.getProfile(cmd.setting())
  File "D:\TOOL\TikTokDownload\Util\Profile.py", line 128, in getProfile
    self.getData(self.api_post_url)
  File "D:\TOOL\TikTokDownload\Util\Profile.py", line 178, in getData
    self.getVideoInfo(result)
  File "D:\TOOL\TikTokDownload\Util\Profile.py", line 290, in getVideoInfo
    datas = Util.Images().get_all_images(self.image_list)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\TOOL\TikTokDownload\Util\Images.py", line 54, in get_all_images
    js = Util.json.loads(r)
         ^^^^^^^^^^^^^^^^^^
  File "D:\Program Files (x86)\Anaconda\envs\tiktok\Lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Program Files (x86)\Anaconda\envs\tiktok\Lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Program Files (x86)\Anaconda\envs\tiktok\Lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
**桌面（请填写以下信息）：**
windows10 64bit]-vpn代理开启
-版本[如1.2.3]

**附文**
在此处添加有关此问题的文字。

**Comment by Johnserf-Seed** [comment]
这是接口返回的这条作品数据里没有图集数据的键，可以提供一下主页链接吗

**Comment by hubbylei** [comment]
带上cookie就解决了，我是删除了Image.py里的self.headers，从Profile.py传过来了个headers
def get_all_images(self, aweme_id,headers):
别的可自行理解 :)

**Comment by CCMonkeyss** [comment]
> 带上cookie就解决了，我是删除了Image.py里的self.headers，从Profile.py传过来了个headers def get_all_images(self, aweme_id,headers): 别的可自行理解 :)

你好，这步是怎么导入headers到image.py的呢，可以教教我吗？我也是卡在这一步，谢谢你。

**Comment by whitebeard916** [comment]
> > 带上cookie就解决了，我是删除了Image.py里的self.headers，从Profile.py传过来了个headers def get_all_images(self, aweme_id,headers): 别的可自行理解 :)
> 
> 你好，这步是怎么导入headers到image.py的呢，可以教教我吗？我也是卡在这一步，谢谢你。

你给Profile.py文件的大概290行左右的datas = Util.Images().get_all_images(self.image_list)加个实参self.headers，改成
datas = Util.Images().get_all_images(self.image_list,self.headers)，然后image.py里面的get_all_images函数加个形参，名字自己起一个，然后函数里面的语句r = Util.requests.get(url=jx_url, headers=self.headers).text的self.headers改成自己的形参就行了。
原因：get_all_images函数里面的self.headers没有cookie，但是Profile.py里面的self.headers有cookie，很奇怪也不知道哪里出问题了

**Comment by CCMonkeyss** [comment]
> > > 带上cookie就解决了，我是删除了Image.py里的self.headers，从Profile.py传过来了个headers def get_all_images(self, aweme_id,headers): 别的可自行理解 :)
> > 
> > 
> > 你好，这步是怎么导入headers到image.py的呢，可以教教我吗？我也是卡在这一步，谢谢你。
> 
> 你给Profile.py文件的大概290行左右的datas = Util.Images().get_all_images(self.image_list)加个实参self.headers，改成 datas = Util.Images().get_all_images(self.image_list,self.headers)，然后image.py里面的get_all_images函数加个形参，名字自己起一个，然后函数里面的语句r = Util.requests.get(url=jx_url, headers=self.headers).text的self.headers改成自己的形参就行了。 原因：get_all_images函数里面的self.headers没有cookie，但是Profile.py里面的self.headers有cookie，很奇怪也不知道哪里出问题了

试了一下，我应该操作对了，问题改善了，谢谢你

**Comment by Johnserf-Seed** [comment]
新版废弃Image了，我现在还在处理所有的issues等待提交吧
