### ISSUE TITLE
终于解决啦！！！Util\XB.py", line 50, in getXbogus UnboundLocalError: local variable 'response' referenced before assignment

### ISSUE THREAD

**Issue by WWRichard** [Johnserf-Seed/TikTokDownload#361]
``**描述出现的错误**
对bug的清晰而简洁的描述。
运行代码下载视频时出现如下错误
[  错误  ]:Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "D:\Tiktok\TikTokDownload-main\example.py", line 19, in <module>
    TK.video_download(line, "no", downloadFold + '/' + nowTime)
  File "D:\Tiktok\TikTokDownload-main\TikTokDownload.py", line 142, in video_download
    jx_url = Util.Urls().POST_DETAIL + Util.XBogus(
  File "D:\Tiktok\TikTokDownload-main\Util\XB.py", line 31, in __init__
    self.getXbogus(url)
  File "D:\Tiktok\TikTokDownload-main\Util\XB.py", line 50, in getXbogus
    self.params = response["result"][0]["paramsencode"]
UnboundLocalError: local variable 'response' referenced before assignment
**bug复现**
复现这次行为的步骤：
1.更改了什么什么
2.点击了什么什么
3.“……”

**截图**
如果适用，添加屏幕截图以帮助解释您的问题。
![230321_22-28-30](https://user-images.githubusercontent.com/71507408/226637900-9643f980-96c4-48a5-aed1-e3e25d45cf4d.jpg)

**桌面（请填写以下信息）：**
-操作系统：[例如windows10 64bit]
-vpn代理[例如开启、关闭]
-版本[如1.2.3]

**附文**
=====================问题解决了！！！！！！！！
首先，之前使用不运行最外层那个   server.bat  是可以正常下载的，后来不知道哪天，就不行了，然后就需要输入Cookies，再后来又不行了， 出现in getXbogus UnboundLocalError: local variable 'response' referenced before assignment这个错误
解决完整的解决步骤如下。
重新下载了完整的项目原码
cd  TikTokDownload-main         #进源码目录
python -m venv env                   #创建虚拟环境，不然安装依赖容易因为版本冲突出错
.\env\Scripts\activate                 #进入虚拟环境
pip install -r requirements.txt    #安装依赖，安装node软件就自已百度了，我之前装过
cd Util                                        #进入Util目录
npm i                                         #安装node依赖
cd ..                                            #退回上层目录
.\server.bat                                 #运行服务
![230331_15-05-07](https://user-images.githubusercontent.com/71507408/229047926-d7cb31a3-f4c2-4e94-8553-b6eeed31749f.jpg)
服务运行成功的效果
![230331_15-11-06](https://user-images.githubusercontent.com/71507408/229049262-3df65917-dc6b-43ae-9915-ea331d65bb76.jpg)
打开conf.ini, 设置cookie
![230331_15-14-10](https://user-images.githubusercontent.com/71507408/229049897-75f49f60-91c8-494f-aefd-4d37848a27a8.jpg)
重新打开一个终端
.\env\Scripts\activate                 #进入虚拟环境
 python .\TikTokDownload.py -u "你要下载的视频链接"       
就可以正常下载啦     
有问题可以问我
![230331_15-23-28](https://user-images.githubusercontent.com/71507408/229052109-368f5dea-b9ff-476a-beee-d7be71035263.jpg)
![230331_15-36-18](https://user-images.githubusercontent.com/71507408/229057615-ab9794c6-28cd-4adc-ae5d-8d9318b94b99.jpg)
![230331_18-04-36](https://user-images.githubusercontent.com/71507408/229090938-946bf7d8-541b-4e69-adc0-6d04b380fd10.jpg)

```python
def download(video_url, music_url, video_title, music_title, headers, music, name):
    # 视频下载
    if video_url == '':
        print('[  提示  ]:该视频可能无法下载哦~\r')
        return
    else:
        r = requests.get(url=video_url, headers=headers)
        if not Util.Status_Code(r.status_code):
            if video_title == '':
                video_title = '[  提示  ]:此视频没有文案_%s\r' % music_title
            video_title = Util.replaceT(video_title)
            music_title = Util.replaceT(music_title)
            if name == "":
                name = video_title
            else:
                if not os.path.exists(name):
                    os.makedirs(name)
                name += '/' + video_title
            with open(f'{name}.mp4', 'wb') as f:
                f.write(r.content)
                print('[  视频  ]:%s.mp4 下载完成\r' % name)

    if music_url == '':
        print('[  提示  ]:下载出错\r')
        # return
    else:
        # 原声下载
        if music != 'yes':
            print('[  提示  ]:不下载%s视频原声\r' % video_title)
            # return
        else:
            r = requests.get(url=music_url, headers=headers)
            with open(f'{music_title}.mp3', 'wb') as f:
                f.write(r.content)
                print('[  音频  ]:%s.mp3 下载完成\r' % music_title)
            # return
``` 

```python
import TikTokDownload as TK
import os
import time
import Util
# 单视频下载
# TK.video_download(*TK.main())
urlsFileName = 'DouYingDownloadUrls.txt'
downloadFold = 'Download'
if not os.path.exists(urlsFileName):
    print('请将需要下载的抖音链接放在 ' + urlsFileName + ' 文件中，每行一个链接')
else:
    if not os.path.exists(downloadFold):
        os.mkdir(downloadFold)
    nowTime = time.strftime("%Y%m%d%H")
    with open(urlsFileName, encoding='utf-8') as fh:
        txt = fh.read().split('\n')
    cmd = Util.Command()
    headers = Util.Cookies(cmd.setting()).dyheaders
    for line in txt:
        if line.strip() == "":
            continue
        TK.video_download(line, "no", downloadFold + '/' + nowTime, headers)
```

call .\env\Scripts\activate
python example.py
pause

**Comment by eightrivers** [comment]
出现同样的错误：HTTPConnectionPool(host='47.115.200.238', port=80): Max retries exceeded with url: /xg/path?url=sec_user_id=MS4wLjABAAAA8AIINGj240azZm5XhR7kiIcGh--VxzHoskD7gkzyw7Q%26count=35%26max_cursor=0%26aid=1128%26version_name=23.5.0%26device_platform=android%26os_version=2333 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001AF59148FD0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))

Win 11 中文 x64最新版，每次都会复现。

跪请大神出手！

**Comment by zfanxingzz** [comment]
频繁请求后，出现了的同样的问题

**Comment by WWRichard** [comment]
有人传说是IP被封，可是我用手机共享的热点也是报这个错呀

**Comment by dd-hf** [comment]
我也是，怎么解决啊

**Comment by BrandyLeeee** [comment]
+1

**Comment by xx254** [comment]
这个是 python/pip/PyQt6 的版本问题, 我是直接下载的 PyQt6, 这个问题就解决了, 你可以试试看
然后我出现了新的问题 -> https://github.com/Johnserf-Seed/TikTokDownload/issues/360
--> 顺便歪楼问一下, 有没有个 discord 或者 微信群可以讨论 issue/bug 的呀, 这样解决问题好慢哈哈
没有的话我拉一个
![5751679778488_ pic](https://user-images.githubusercontent.com/20279502/227742031-dd3a690c-b9c3-4933-ae20-e0665c537797.jpg)

**Comment by hubbylei** [comment]
> 出现同样的错误：HTTPConnectionPool(host='47.115.200.238', port=80): Max retries exceeded with url: /xg/path?url=sec_user_id=MS4wLjABAAAA8AIINGj240azZm5XhR7kiIcGh--VxzHoskD7gkzyw7Q%26count=35%26max_cursor=0%26aid=1128%26version_name=23.5.0%26device_platform=android%26os_version=2333 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001AF59148FD0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
> 
> Win 11 中文 x64最新版，每次都会复现。
> 
> 跪请大神出手！

你这个绝对不是最新版，xg这个已经改成本地服务了

**Comment by eightrivers** [comment]
> 

恩，谢谢指导！ 这个错误对应的确实不是最新版。我刚刷了最新版本，还是报类似的错误。错误信息如下：

![image](https://user-images.githubusercontent.com/1868294/228862986-abe0b7df-bde6-431d-9e1d-b8ef211e6843.png)

cookie配置如下：

![image](https://user-images.githubusercontent.com/1868294/228863197-3f426fa2-62eb-48ed-b33b-4a26b0b1633a.png)

**Comment by WWRichard** [comment]
> 出现同样的错误：HTTPConnectionPool(host='47.115.200.238', port=80): Max retries exceeded with url: /xg/path?url=sec_user_id=MS4wLjABAAAA8AIINGj240azZm5XhR7kiIcGh--VxzHoskD7gkzyw7Q%26count=35%26max_cursor=0%26aid=1128%26version_name=23.5.0%26device_platform=android%26os_version=2333 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001AF59148FD0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
> 
> Win 11 中文 x64最新版，每次都会复现。
> 
> 跪请大神出手！

我的解决了，看上面
