### ISSUE TITLE
[BUG]运行异常

### ISSUE THREAD

**Issue by summer990** [Johnserf-Seed/TikTokDownload#381]
异常退出：
Traceback (most recent call last):
  File "C:\Users\admin\Desktop\tk\TikTokDownload-main\TikTokTool.py", line 32, in <module>
    profile.getProfile(cmd.setting())
  File "C:\Users\admin\Desktop\tk\TikTokDownload-main\Util\Profile.py", line 128, in getProfile
    self.getData(self.api_post_url)
  File "C:\Users\admin\Desktop\tk\TikTokDownload-main\Util\Profile.py", line 178, in getData
    self.getVideoInfo(result)
  File "C:\Users\admin\Desktop\tk\TikTokDownload-main\Util\Profile.py", line 290, in getVideoInfo
    datas = Util.Images().get_all_images(self.image_list)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\Desktop\tk\TikTokDownload-main\Util\Images.py", line 54, in get_all_images
    js = Util.json.loads(r)
         ^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
![image](https://user-images.githubusercontent.com/52158736/228845823-04554921-100f-4266-8e50-e8e3c38f0c34.png)

**Comment by WWRichard** [comment]
去看看[https://github.com/Johnserf-Seed/TikTokDownload/issues/361](url)
