### ISSUE TITLE
[BUG]无法下载

### ISSUE THREAD

**Issue by Enerald** [Johnserf-Seed/TikTokDownload#422]
[  错误  ]:Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "C:\Users\mmeng\Downloads\Software\TikTokDownload\TikTokDownload-main\TikTokTool.py", line 32, in <module>
    profile.getProfile(cmd.setting())
  File "C:\Users\mmeng\Downloads\Software\TikTokDownload\TikTokDownload-main\Util\Profile.py", line 84, in getProfile
    datas = Util.XBogus('aid=6383&sec_user_id=%s&count=35&max_cursor=0&cookie_enabled=true&platform=PC&downlink=10' % (
  File "C:\Users\mmeng\Downloads\Software\TikTokDownload\TikTokDownload-main\Util\XB.py", line 30, in __init__
    self.getXbogus(url)
  File "C:\Users\mmeng\Downloads\Software\TikTokDownload\TikTokDownload-main\Util\XB.py", line 50, in getXbogus
    self.params = response["result"][0]["paramsencode"]
UnboundLocalError: local variable 'response' referenced before assignment

感谢大佬们的帮助和解答~

**Comment by peterdocter** [comment]
还有要启动本地Server.py,不过douyin好像变了还有错误提示没有md5模块

**Comment by peterdocter** [comment]
TikTokDownload-main\Util>python3.10 Server.py
 * Serving Flask app 'Server'
 * Debug mode: off
WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8889
 * Running on http://192.168.100.193:8889
Press CTRL+C to quit
127.0.0.1 - - [04/May/2023 18:11:48] "POST /xg/path?url=aweme_id=7052212207483899143%26aid=6383%26cookie_enabled=true%26platform=PC%26downlink=10 HTTP/1.1" 308 -
[2023-05-04 18:11:49,186] ERROR in app: Exception on /xg/path/ [POST]
Traceback (most recent call last):
  File "D:\Development\SetEnv\Python\Python310\lib\site-packages\flask\app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\Development\SetEnv\Python\Python310\lib\site-packages\flask\app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\Development\SetEnv\Python\Python310\lib\site-packages\flask\app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\Development\SetEnv\Python\Python310\lib\site-packages\flask\app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "D:\PythonTools\TikTokDownload\TikTokDownload-main\Util\Server.py", line 123, in xgpath
    return server.getXG(url_path, params)
  File "D:\PythonTools\TikTokDownload\TikTokDownload-main\Util\Server.py", line 38, in getXG
    xbogus = self.xbogust_func.call("getXB", url_path)
  File "D:\Development\SetEnv\Python\Python310\lib\site-packages\execjs\_abstract_runtime_context.py", line 37, in call
    return self._call(name, *args)
  File "D:\Development\SetEnv\Python\Python310\lib\site-packages\execjs\_external_runtime.py", line 92, in _call
    return self._eval("{identifier}.apply(this, {args})".format(identifier=identifier, args=args))
  File "D:\Development\SetEnv\Python\Python310\lib\site-packages\execjs\_external_runtime.py", line 78, in _eval
    return self.exec_(code)
  File "D:\Development\SetEnv\Python\Python310\lib\site-packages\execjs\_abstract_runtime_context.py", line 18, in exec_
    return self._exec_(source)
  File "D:\Development\SetEnv\Python\Python310\lib\site-packages\execjs\_external_runtime.py", line 88, in _exec_
    return self._extract_result(output)
  File "D:\Development\SetEnv\Python\Python310\lib\site-packages\execjs\_external_runtime.py", line 167, in _extract_result
    raise ProgramError(value)
execjs._exceptions.ProgramError: Error: Cannot find module 'md5'
Require stack:
- D:\PythonTools\TikTokDownload\TikTokDownload-main\Util\[stdin]
127.0.0.1 - - [04/May/2023 18:11:49] "POST /xg/path/?url=aweme_id=7052212207483899143%26aid=6383%26cookie_enabled=true%26platform=PC%26downlink=10 HTTP/1.1" 500 -

**Comment by hubbylei** [comment]
进入Util文件夹，输入npm i 安装node依赖
