### ISSUE TITLE
小白求助二----目前已经是13054版本（最新）

### ISSUE THREAD

**Issue by FigoY** [Johnserf-Seed/TikTokDownload#426]
[   💻   ]:Windows平台
[   🗻   ]:获取最新版本号中!
[   🌋   ]:获取网络版本号失败!
[   🚩   ]:目前 13054 版本已是最新
[  警告  ]:未检测到命令，将使用配置文件进行批量下载!
[  提示  ]:读取本地配置完成!
[  提示  ]:批量获取所有视频中!
[  提示  ]:用户的sec_id=MS4wLjABAAAAoh3-GNimLQTbYbPB-TvbCXS7o530IPa6VNhMykrcT5A
[  错误  ]:HTTPConnectionPool(host='47.115.200.238', port=80): Max retries exceeded with url: /xg/path?url=sec_user_id=MS4wLjABAAAAoh3-GNimLQTbYbPB-TvbCXS7o530IPa6VNhMykrcT5A%26count=35%26max_cursor=0%26aid=1128%26version_name=23.5.0%26device_platform=android%26os_version=2333 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001BE0027FDD0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
Traceback (most recent call last):
  File "TikTokTool.py", line 29, in <module>
    profile.getProfile(cmd.setting())
  File "Util\Profile.py", line 82, in getProfile
    datas = Util.XBogus('sec_user_id=%s&count=35&max_cursor=0&aid=1128&version_name=23.5.0&device_platform=android&os_version=2333' % (
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "Util\XB.py", line 30, in __init__
    self.getXbogus(url)
  File "Util\XB.py", line 50, in getXbogus
    self.params = response["result"][0]["paramsencode"]
                  ^^^^^^^^
UnboundLocalError: cannot access local variable 'response' where it is not associated with a value
[10448] Failed to execute script 'TikTokTool' due to unhandled exception!

**Comment by namedssy** [comment]
您好解决了吗  我也遇到这个问题了，主页链接格式和文件里的不一样啊

**Comment by namedssy** [comment]
您好  想问下 您的sec_id 是哪里来的啊

**Comment by namedssy** [comment]
我复制出来的主页链接是这样的  “https://www.tiktok.com/@mikkyklayker?lang=zh-Hans&is_from_webapp=1&sender_device=mobile&sender_web_id=7225173950042342958”  你的格式也是这样吗

**Comment by hubbylei** [comment]
最新版是13080

**Comment by chenkongming** [comment]
@hubbylei 13080也不行了

**Comment by chenkongming** [comment]
要先跑serve.bat

**Comment by Telunx** [comment]
> 最新版是13080

你是怎么更新到13080的？ 我一直提示 网络不太通畅，请重新运行

**Comment by Telunx** [comment]
[   💻   ]:Windows平台
[   🗻   ]:获取最新版本号中!
[   🌋   ]:当前不是最新版本,需要升级吗? (y/n) :y
[   🚩   ]:正在为你下载 13080 版本中，升级前请确保关闭所有打开的项目文件
[   🚧   ]:网络不太通畅，请重新运行

**Comment by Mak0760** [comment]
> [ 🌋 ]:当前不是最新版本,需要升级吗? (y/n) :y [ 🚩 ]:正在为你下载 13080 版本中，升级前请确保关闭所有打开的项目文件 [ 🚧 ]:网络不太通畅，请重新运行

试一下更换一下网络环境并重复关闭开启更新
