### ISSUE TITLE
[BUG]按照步骤来时，启动server.py报错

### ISSUE THREAD

**Issue by Winyer** [Johnserf-Seed/TikTokDownload#430]
**描述出现的错误**
对bug的清晰而简洁的描述。
启动server.py报错如下：
 * Serving Flask app 'Server'
 * Debug mode: off
Traceback (most recent call last):
  File "Server.py", line 177, in <module>
    server.app.run(host='0.0.0.0',port='8889')
  File "C:\Python\lib\site-packages\flask\app.py", line 1188, in run
    run_simple(t.cast(str, host), port, self, **options)
  File "C:\Python\lib\site-packages\werkzeug\serving.py", line 1075, in run_simple
    srv = make_server(
  File "C:\Python\lib\site-packages\werkzeug\serving.py", line 915, in make_server
    return ThreadedWSGIServer(
  File "C:\Python\lib\site-packages\werkzeug\serving.py", line 748, in __init__
    self.server_bind()
  File "C:\Python\lib\http\server.py", line 140, in server_bind
    self.server_name = socket.getfqdn(host)
  File "C:\Python\lib\socket.py", line 756, in getfqdn
    hostname, aliases, ipaddrs = gethostbyaddr(name)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb5 in position 4: invalid start byte

**bug复现**
复现这次行为的步骤：.\server.bat或者python .\server.py
1.更改了什么什么
2.点击了什么什么
3.“……”
无
**截图**
如果适用，添加屏幕截图以帮助解释您的问题。

**桌面（请填写以下信息）：**
-操作系统：
windows10 64bit
-vpn代理[例如开启、关闭] 
关闭
-版本[如1.2.3]
13080
**附文**
在此处添加有关此问题的文字。

**Comment by Winyer** [comment]
解决了，python版本不满足要求引起的问题，更新后解决
