### ISSUE TITLE
[BUG]下载报错 我代码小白 正在学习 运行是3.1.1的python 

### ISSUE THREAD

**Issue by fungchunhoeasy** [Johnserf-Seed/TikTokDownload#432]
Traceback (most recent call last):
  File "F:\抖音视频下载\TikTokTool.py", line 32, in <module>
    profile.getProfile(cmd.setting())
  File "F:\抖音视频下载\Util\Profile.py", line 84, in getProfile
    datas = Util.XBogus('aid=6383&sec_user_id=%s&count=35&max_cursor=0&cookie_enabled=true&platform=PC&downlink=10' % (
  File "F:\抖音视频下载\Util\XB.py", line 30, in __init__
    self.getXbogus(url)
  File "F:\抖音视频下载\Util\XB.py", line 50, in getXbogus
    self.params = response["result"][0]["paramsencode"]
UnboundLocalError: cannot access local variable 'response' where it is not associated with a value

请问各位大神要怎么解决？
跪求！！！！

**Comment by fungchunhoeasy** [comment]
有大神指导下麻

**Comment by Mak0760** [comment]
是不是没有先运行server.bat

**Comment by fungchunhoeasy** [comment]
已经运行了 先运行server.bat的

**Comment by ZaiKL** [comment]
进入Util文件夹，输入npm i 安装node依赖

**Comment by fungchunhoeasy** [comment]
已经输入了安装了 还是不行 还是最上方的报错显示

**Comment by Johnserf-Seed** [comment]
![image](https://github.com/Johnserf-Seed/TikTokDownload/assets/40727745/51b3b1a5-1fa5-42f6-b80b-e41a59c2c574)

**Comment by fungchunhoeasy** [comment]
我是最新版的额 目前3.11.4 我全部删除重新下载试试

**Comment by fungchunhoeasy** [comment]
可以了 谢谢给位！！！！~~~~

**Comment by fungchunhoeasy** [comment]
前天解决了 昨天出现 “获取用户数据失败，请从web端获取新ttwid填入配置文件”
然后重新复制后正常。
今天继续出现 “获取用户数据失败，请从web端获取新ttwid填入配置文件” 然后重新复制cookie也不行了 全部复制的都是
