### ISSUE TITLE
[BUG] 启动说 profile 初始化缺少header ？ 我加了个浏览器header进去，报 连接创建异常错误，为什么呢

### ISSUE THREAD

**Issue by ldh127** [Johnserf-Seed/TikTokDownload#434]
**描述出现的错误**
对bug的清晰而简洁的描述。

**bug复现**
复现这次行为的步骤：
1.更改了什么什么
2.点击了什么什么
3.“……”

**截图**
如果适用，添加屏幕截图以帮助解释您的问题。

**桌面（请填写以下信息）：**
-操作系统：[例如windows10 64bit]
-vpn代理[例如开启、关闭]
-版本[如1.2.3]

**附文**
在此处添加有关此问题的文字。

**Comment by ldh127** [comment]
问题修改了，我用的是老版本的example，更新了example.py ，代码里带了  header ，但是依然response返回为空，

[   🚩   ]:目前 13080 版本已是最新
[  警告  ]:未检测到命令，将使用配置文件进行批量下载!
[  提示  ]:读取本地配置完成!
[  警告  ]:未检测到命令，将使用配置文件进行批量下载!
[  提示  ]:读取本地配置完成!
[  提示  ]:批量获取所有视频中!
[  提示  ]:用户的sec_id=MS4wLjABAAAAj58xzuWsn5KU_0NXPVYizwV7IfEKJIw2BKDf7eO1DeqRiFQTPcpdU31vlZe2fMLl
[  错误  ]:HTTPConnectionPool(host='127.0.0.1', port=8889): Max retries exceeded with url: /xg/path?url=aid=6383%26sec_user_id=MS4wLjABAAAAj58xzuWsn5KU_0NXPVYizwV7IfEKJIw2BKDf7eO1DeqRiFQTPcpdU31vlZe2fMLl%26count=35%26max_cursor=0%26cookie_enabled=true%26platform=PC%26downlink=10 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f94ede25b10>: Failed to establish a new connection: [Errno 111] Connection refused'))
response: {}
Traceback (most recent call last):
  File "batch_down.py", line 17, in <module>
    profile.getProfile(cmd.setting())
  File "/home/ubuntu/all_root/workspace_root/jupyter_workspace/TikTokDownload/Util/Profile.py", line 85, in getProfile
    self.sec))
  File "/home/ubuntu/all_root/workspace_root/jupyter_workspace/TikTokDownload/Util/XB.py", line 30, in __init__
    self.getXbogus(url)
  File "/home/ubuntu/all_root/workspace_root/jupyter_workspace/TikTokDownload/Util/XB.py", line 54, in getXbogus
    self.params = response["result"][0]["paramsencode"]
KeyError: 'result'

**Comment by ldh127** [comment]
问题已经解决： flask 版本问题
Werkzeug <= 2.1.2   
flask == 2.1.2    完美运行
