### ISSUE TITLE
[Feature] VR180/360 Video + Livestream | VR180/360 视频 + 直播

### ISSUE THREAD

**Issue by scribe2433** [Johnserf-Seed/TikTokDownload#464]
[English]
Is there a way to download VR180/360 video + livestream?

I found that, PC version doesn't show VR360 video on Creator's page. When using TikTokDownload.py, it will not download these VR360 video. These VR360 video only show up on Creator's page if i use Douyin APP. 

I also tried sharing link from my Douyin APP, but when I open the link (even in both PC and mobile APP), it says video not found.

For Livestream, when I share Livestream Link from my Douyin APP, I can open it on my PC and see stream, but it will tell me only available for mobile viewing (tell me to scan QR code on my douyin APP). 

When I use TikTokLive.exe, it will give error: 

Traceback (most recent call last):
  File "TikTokLive.py", line 25, in <module>
IndexError: list index out of range
[10400] Failed to execute script 'TikTokLive' due to unhandled exception!

I assume it is because of the mobile restriction. 

[中文]
先说我中文不太好，抱歉如果打错几个字。

请问有方法下载 VR180/360 视频 + 直播吗？

我发现如果用手提电脑，在主播户口看不到VR360的视频（根本没出现）。用TikTokDownload.py，也不会下载这些视频。如果我用手机抖音APP才能看到。 

我试了从我的手机抖音分享视频，可是我开了链接，在手机上和电脑上，都会说视频找不到。

说直播，我用手机的抖音分享链接，电脑开的到，可是它会说该内容仅限手机观看，叫我打开抖音，扫一扫。

我用TikTokLive.exe试试后，出了这个问题：

Traceback (most recent call last):
  File "TikTokLive.py", line 25, in <module>
IndexError: list index out of range
[10400] Failed to execute script 'TikTokLive' due to unhandled exception!

我才是因为需要手机的问题吧？

**Comment by Johnserf-Seed** [comment]
这个issue有意思，我还没试过全景直播的采集。如果仅限手机观看，web的接口没有数据的话暂时还无法采集
