### ISSUE TITLE
[BUG] File name too long

### ISSUE THREAD

**Issue by cws999** [Johnserf-Seed/TikTokDownload#469]
**描述出现的错误**
视频描述文字太长，下载失败

**bug复现**
下载某用户的所有视频
1. ./TikTokTool.py -u https://www.douyin.com/user/MS4wLjABAAAANU_sBeESJD5UFsFCoj9mttQLBt3TBKeAWJ5sL5oajMk

Traceback (most recent call last):
  File "/XXXXX/TikTokDownload-main/./TikTokTool.py", line 32, in <module>
    profile.getProfile(cmd.setting())
  File "/XXXXX/TikTokDownload-main/Util/Profile.py", line 132, in getProfile
    self.getData(self.api_post_url)
  File "/XXXXX/TikTokDownload-main/Util/Profile.py", line 182, in getData
    self.getVideoInfo(result)
  File "/XXXXX/TikTokDownload-main/Util/Profile.py", line 303, in getVideoInfo
    self.getNextData()
  File "/XXXXX/TikTokDownload-main/Util/Profile.py", line 233, in getNextData
    self.getVideoInfo(result)
  File "/XXXXX/TikTokDownload-main/Util/Profile.py", line 303, in getVideoInfo
    self.getNextData()
  File "/XXXXX/TikTokDownload-main/Util/Profile.py", line 233, in getNextData
    self.getVideoInfo(result)
  File "/XXXXX/TikTokDownload-main/Util/Profile.py", line 302, in getVideoInfo
    Util.Download().ImageDownload(datas)
  File "/XXXXX/TikTokDownload-main/Util/Download.py", line 184, in ImageDownload
    Util.os.makedirs(path)
  File "<frozen os>", line 225, in makedirs
OSError: [Errno 36] File name too long: 'Download/pic/广西小吃货/2023-04-05 10.08.17傻瓜_你是不是连初中都没读完_就踏入社会_熬到现在_其实你本身并没有错_错的是在无知的年龄选错了路_在懂事的年纪承担着后果罢了_你说是不是_#00后_#吃不了学习的苦那就得吃生活的__版本过低_升级后'

**桌面（请填写以下信息）：**
-操作系统：[devuan 5 ]
-版本[13090]

**附文**
视频的描述文字太长，下载失败
视频的描述文字不长，下载成功

**Comment by zjplab** [comment]
https://stackoverflow.com/questions/6571435/limit-on-file-name-length-in-bash
@Johnserf-Seed  文件系统是有文件名长度限制的 可以在用`Utils.os.mkdir`之前做截断

**Comment by Johnserf-Seed** [comment]
> https://stackoverflow.com/questions/6571435/limit-on-file-name-length-in-bash @Johnserf-Seed 文件系统是有文件名长度限制的 可以在用`Utils.os.mkdir`之前做截断

https://learn.microsoft.com/zh-cn/windows/win32/fileio/maximum-file-path-limitation?tabs=registry
是的一般的操作系统只支持255位、260位字符 此前没考虑到过长的视频文案

**Comment by cws999** [comment]
> > https://stackoverflow.com/questions/6571435/limit-on-file-name-length-in-bash @Johnserf-Seed 文件系统是有文件名长度限制的 可以在用`Utils.os.mkdir`之前做截断
> 
> https://learn.microsoft.com/zh-cn/windows/win32/fileio/maximum-file-path-limitation?tabs=registry 是的一般的操作系统只支持255位、260位字符 此前没考虑到过长的视频文案

1.4的版本还是有此错误发生
[  提示  ]:异常，[Errno 36] File name too long: 
'/TikTokDownload-1.4.0.0/Download/post/meiyu晓萱内衣裤严选/2023-08-18 
16.30.00_还没想好七夕给女朋友送什么礼物吗_那就安排这款冰皮内裤吧_穿上身真的太舒服了_冰冰凉凉_丝丝滑滑_好穿不贵_#
新品上新_#大数据是不会乱推的_#七夕_#男朋友_#七夕我要种草浪漫'
[2023-08-19 22:12:04,354] - Log.py] - ERROR: [  提示  ]:异常，[Errno 36] File name too long: '/TikTokDownload-1.4.0.0/Download/post/meiyu晓萱内衣裤严选/2023-08-18 16.30.00_还没想好七夕给女朋友送什么礼物吗_那就安排这款冰皮内裤吧_穿上身真的太舒服了_冰冰凉凉_丝丝滑滑_好穿不贵_#新品上新_#大数据是不会乱推的_#七夕_#男朋友_#七夕我要种草浪漫'

**Comment by Johnserf-Seed** [comment]
#483
