### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by xty8623** [Johnserf-Seed/TikTokDownload#482]
大佬你好，我这边发现tiktok的视频合集下载每次都报错，可能是因为tiktok的主页链接和抖音不同。我试了下载抖音的个人合集没有问题。tiktok的主页链接是https://www.tiktok.com/@soon_ne，也试过您主页提供的链接也不行。能麻烦解答一下吗，感谢
Traceback (most recent call last):
  File "C:\Users\XTY\Desktop\test\TikTokTool.py", line 32, in <module>
    profile.getProfile(cmd.setting())
  File "C:\Users\XTY\Desktop\test\Util\Profile.py", line 72, in getProfile
    print('[  提示  ]:用户的sec_id=%s\r' % self.sec)
AttributeError: 'Profile' object has no attribute 'sec'

**Comment by Neo010Lee** [comment]
你解决了吗？？？我的也是这样，抖音就可以。tiktok不行
