### ISSUE TITLE
[BUG] 程序报错：Traceback

### ISSUE THREAD

**Issue by EsperantoP** [Johnserf-Seed/TikTokDownload#484]
**描述出现的错误**

在Git Bash内执行./tiktoktool.py时，输出“未检测到命令，将使用配置文件进行批量下载!‘

并在之后弹出：
Traceback (most recent call last):
  File "C:\Users\#####\Desktop\TK Dl\TikTokDownload-main\tiktoktool.py", line 32, in <module>
    profile.getProfile(cmd.setting())
  File "C:\Users\#####\Desktop\TK Dl\TikTokDownload-main\Util\Profile.py", line 95, in getProfile
    post_name_json = Util.json.loads(response.content.decode())
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\#####\AppData\Local\Programs\Python\Python311\Lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\#####\AppData\Local\Programs\Python\Python311\Lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\#####\AppData\Local\Programs\Python\Python311\Lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**bug复现**
复现这次行为的步骤：

1.更改了什么什么：
我没有更改任何文件及格式。仅更改过conf.ini内的uid值及cookie值

2.点击了什么什么：
N/A

3. 根据以往的操作步骤操作的，然是今天就报错了 :)

**截图**
如果适用，添加屏幕截图以帮助解释您的问题。
![image](https://github.com/Johnserf-Seed/TikTokDownload/assets/81968849/0ea4081e-feea-454c-8e76-100a764099bf)

**桌面（请填写以下信息）：**
-操作系统：Windows 10 Pro
-vpn代理：[关闭]
-版本：[13090]

**附文**
N/A

**Comment by HOOCCH2COOH** [comment]
同样的问题，有时候会碰到，昨天是正常的。

**Comment by ivivivivivivi** [comment]
我也遇到了，后来发现是没有用管理员权限打开，导致文件读取权限的问题，你可以试一下，说不定也是同样的原因

**Comment by EsperantoP** [comment]
嗯。。好吧，就在刚刚，又尝试了一下，好使了。。但是也请开发者了解一下这个问题

**Comment by EsperantoP** [comment]
> 

非常好，报错又来了 :)

**Comment by EsperantoP** [comment]
**这是最新报错**

Traceback (most recent call last):
  File "C:\Users\45760\Desktop\TK Dl\TikTokDownload-main\tiktoktool.py", line 32, in <module>
    profile.getProfile(cmd.setting())
  File "C:\Users\45760\Desktop\TK Dl\TikTokDownload-main\Util\Profile.py", line 132, in getProfile
    self.getData(self.api_post_url)
  File "C:\Users\45760\Desktop\TK Dl\TikTokDownload-main\Util\Profile.py", line 182, in getData
    self.getVideoInfo(result)
  File "C:\Users\45760\Desktop\TK Dl\TikTokDownload-main\Util\Profile.py", line 303, in getVideoInfo
    self.getNextData()
  File "C:\Users\45760\Desktop\TK Dl\TikTokDownload-main\Util\Profile.py", line 233, in getNextData
    self.getVideoInfo(result)
  File "C:\Users\45760\Desktop\TK Dl\TikTokDownload-main\Util\Profile.py", line 303, in getVideoInfo
    self.getNextData()
  File "C:\Users\45760\Desktop\TK Dl\TikTokDownload-main\Util\Profile.py", line 224, in getNextData
    html = Util.json.loads(response.content.decode())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\45760\AppData\Local\Programs\Python\Python311\Lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\45760\AppData\Local\Programs\Python\Python311\Lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\45760\AppData\Local\Programs\Python\Python311\Lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by EsperantoP** [comment]
这个报错貌似可以i通过刷新目标连接网页，完成人机验证来解决。太玄学了

**Comment by AppeiAmanda** [comment]
> 这个报错貌似可以i通过刷新目标连接网页，完成人机验证来解决。太玄学了
爬取数据太频繁，被抖音后台标记了

**Comment by Johnserf-Seed** [comment]
因为风控了所以接口不返回了，去web过一下验证码就可以了。触发人机验证就顾名思义，太频繁了

**Comment by ivivivivivivi** [comment]
> 因为风控了所以接口不返回了，去web过一下验证码就可以了。触发人机验证就顾名思义，太频繁了

可是网页并没有验证码，还是可以刷新的

**Comment by Johnserf-Seed** [comment]
等新版推送，新版可以直接手机扫码登录

**Comment by EsperantoP** [comment]
> 因为风控了所以接口不返回了，去web过一下验证码就可以了。触发人机验证就顾名思义，太频繁了

正确的，挑明的，一针见血的。

**Comment by EsperantoP** [comment]
补充：貌似在下载完成所有视频之后，同样会报错而不是自动提示退出... 嗯。。

**Comment by Johnserf-Seed** [comment]
![image](https://github.com/Johnserf-Seed/TikTokDownload/assets/40727745/8a16a705-0537-49f8-9062-d5cfb9266ad4)
![image](https://github.com/Johnserf-Seed/TikTokDownload/assets/40727745/d9506f26-00a1-4743-963d-43bd83015a8a)
我想到的问题差不多都已经测试通过了，预计晚上就更新新版。新版体验极佳😀

**Comment by EsperantoP** [comment]
> ![image](https://user-images.githubusercontent.com/40727745/258089711-8a16a705-0537-49f8-9062-d5cfb9266ad4.png) ![image](https://user-images.githubusercontent.com/40727745/258089790-d9506f26-00a1-4743-963d-43bd83015a8a.png) 我想到的问题差不多都已经测试通过了，预计晚上就更新新版。新版体验极佳😀

给力啊！

**Comment by Johnserf-Seed** [comment]
> > ![image](https://user-images.githubusercontent.com/40727745/258089711-8a16a705-0537-49f8-9062-d5cfb9266ad4.png) ![image](https://user-images.githubusercontent.com/40727745/258089790-d9506f26-00a1-4743-963d-43bd83015a8a.png) 我想到的问题差不多都已经测试通过了，预计晚上就更新新版。新版体验极佳😀
> 
> 给力啊！

这次重构之后异步下载太快了，2分钟左右下载了800多个作品。现在在写readme，等下就更新

**Comment by AppeiAmanda** [comment]
> > > ![image](https://user-images.githubusercontent.com/40727745/258089711-8a16a705-0537-49f8-9062-d5cfb9266ad4.png) ![image](https://user-images.githubusercontent.com/40727745/258089790-d9506f26-00a1-4743-963d-43bd83015a8a.png) 我想到的问题差不多都已经测试通过了，预计晚上就更新新版。新版体验极佳😀
> > 
> > 
> > 给力啊！
> 
> 这次重构之后异步下载太快了，2分钟左右下载了800多个作品。现在在写readme，等下就更新

坐等

**Comment by EsperantoP** [comment]
问题成功解决！
解决方案：程序版本升级至14000！

**Comment by EsperantoP** [comment]
> ![image](https://user-images.githubusercontent.com/40727745/258089711-8a16a705-0537-49f8-9062-d5cfb9266ad4.png) ![image](https://user-images.githubusercontent.com/40727745/258089790-d9506f26-00a1-4743-963d-43bd83015a8a.png) 我想到的问题差不多都已经测试通过了，预计晚上就更新新版。新版体验极佳😀

虽然说已经更新了，但是我还是要说：
血妈快，血妈麻，血妈🐂🍺
