### ISSUE TITLE
[BUG] How to fix this please SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by dinoleeht2m** [Johnserf-Seed/TikTokDownload#507]
C:\Users\dubui\Music\TikTokDownload-main>python example.py
Traceback (most recent call last):
  File "C:\Users\dubui\Music\TikTokDownload-main\example.py", line 17, in <module>
    import Util.NickMapper as NickMapper
  File "C:\Users\dubui\Music\TikTokDownload-main\Util\__init__.py", line 70, in <module>
    from .Login import *
  File "C:\Users\dubui\Music\TikTokDownload-main\Util\Login.py", line 103
    match status:
          ^
SyntaxError: invalid syntax

**Comment by shring56** [comment]
这个错误是因为你的代码中使用了 Python 3.10 引入的新特性 "Structural Pattern Matching" 的语法，而你的运行环境中的 Python 版本可能低于 3.10。作者在readme中也提到：低于Python3.11.1版本可能会有意外的错误。

"Structural Pattern Matching" 是 Python 3.10 中引入的新特性，允许你以一种更直观的方式进行模式匹配。然而，在 Python 3.10 之前的版本中是不支持这种语法的。

**Comment by Johnserf-Seed** [comment]
> C:\Users\dubui\Music\TikTokDownload-main>python example.py Traceback (most recent call last): File "C:\Users\dubui\Music\TikTokDownload-main\example.py", line 17, in import Util.NickMapper as NickMapper File "C:\Users\dubui\Music\TikTokDownload-main\Util__init__.py", line 70, in from .Login import * File "C:\Users\dubui\Music\TikTokDownload-main\Util\Login.py", line 103 match status: ^ SyntaxError: invalid syntax

请使用readme中的python的版本
