### ISSUE TITLE
初级PHPer的使用问题。

### ISSUE THREAD

**Issue by Mr3Zhang** [Johnserf-Seed/TikTokDownload#51]
admin@DESKTOP-E4DSTAB MINGW64 /d/www/ttt
$ python exmple.py
Traceback (most recent call last):
  File "D:\www\ttt\exmple.py", line 3, in <module>
    import TikTokMulti as MTK
  File "D:\www\ttt\TikTokMulti.py", line 13, in <module>
    import TikTokDownload
  File "D:\www\ttt\TikTokDownload.py", line 12, in <module>
    from retrying import retry
ModuleNotFoundError: No module named 'retrying'

大佬，我出现了上面的错误，不知道是哪一步错了，我是初级php，完全没有接触过py

**Comment by Johnserf-Seed** [comment]
$ pip3 install retrying
是这个依赖没有安装
运行exmple.py的时候可以按需求注释掉单视频下载模式，否则会多开

**Comment by Mr3Zhang** [comment]
> $ pip3 install retrying
> 是这个依赖没有安装
> 运行exmple.py的时候可以点选注释掉单视频下载模式，否则会多开

谢谢。
