### ISSUE TITLE
[BUG] Problem with tiktok QR and cookie conflict with douyin url links

### ISSUE THREAD

**Issue by Alexo88** [Johnserf-Seed/TikTokDownload#524]
**Describe the bug that occurs** 
when I open the example.py file I can't capture the QR because it seems to be the douyin QR and not the tiktok QR, so my tiktok app won't process the douyin QR. So nowhere does it say if this QR works for both tiktok and douyin or only for douyin.

On the other hand, when I set the cookies manually, I don't know where to put the tiktok link I want to download so it seems to use a douyin url by default and my cookies are for tiktok, so I get a problem reading .json.

**Bug Reproduction** Steps to reproduce this behaviour: 
```
[   💻   ]:Windows平台
[   🗻   ]:获取最新版本号中!
[   🚩   ]:目前 14200 版本已是最新
[  配置  ]:配置验证成功!
[  配置  ]:读取本地配置完成!
[  提示  ]:异常，链接错误,无法提取用户ID.
[2023-08-20 20:08:34,095] - Log.py] - ERROR: [  提示  ]:异常，链接错误,无法提取用户ID.，Traceback (most recent call last):
  File "D:\- GITHUB repo\TikTokDownload-main\Util\Profile.py", line 450, in get_Profile
    self.sec_user_id = await self.get_all_sec_user_id(inputs=self.config['uid'])
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\- GITHUB repo\TikTokDownload-main\Util\Profile.py", line 164, in get_all_sec_user_id
    raise ValueError("链接错误,无法提取用户ID.")
ValueError: 链接错误,无法提取用户ID.

[  提示  ]：按任意键退出程序!
```

**Screenshot** If applicable, add a screenshot to help explain your issue.

**Desktop (please fill in the following information):** 
- OS: [e.g. windows 11 64bit] - vpn proxy: [ off] - Project version: [ 1.4.2.2] - py version: [3.11.4] 

**Attachment** 
How do I download videos from a tiktok profile, how ?

**Comment by 6986552** [comment]
only for douyin,now
