### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by youzeliang** [Johnserf-Seed/TikTokDownload#529]
**描述出现的错误**
更新完最新的然后就不能运行了，只修改了conf.ini文件里的uid，然后运行 TikTokTool.py 就报错

**bug复现**
复现这次行为的步骤：
1.首先更改了什么什么
2.点击了什么什么
3.“……”

**截图**
如果适用，添加屏幕截图以帮助解释您的问题。

![image](https://github.com/Johnserf-Seed/TikTokDownload/assets/26573169/70738086-a50c-4e5d-b1a1-1b3fcea25218)

**桌面（请填写以下信息）：**
-操作系统：[例如windows10 64bit]
-vpn代理：[例如开启、关闭]
-项目版本：[如1.4.2.2]
-py版本：[如3.11.1]
-依赖库的版本：[出错的库版本号]

**附文**
在此处添加有关此问题的其他备注。

[  提示  ]:异常，网络连接异常，异常：Cannot connect to host www.douyin.com:443 
ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] 
certificate verify failed: self signed certificate in certificate chain 
(_ssl.c:1002)')]
[2023-08-26 13:47:30,817] - Log.py] - ERROR: [  提示  ]:异常，网络连接异常，异常：Cannot connect to host www.douyin.com:443 ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1002)')]，Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/aiohttp/connector.py", line 980, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/base_events.py", line 1112, in create_connection
    transport, protocol = await self._create_connection_transport(
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/base_events.py", line 1145, in _create_connection_transport
    await waiter
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/sslproto.py", line 574, in _on_handshake_complete
    raise handshake_exc
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/sslproto.py", line 556, in _do_handshake
    self._sslobj.do_handshake()
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/ssl.py", line 979, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1002)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/youzeliang/dev/code/python/TikTokDownload/Util/Profile.py", line 160, in get_all_sec_user_id
    match = await self.re_match(session, inputs)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/youzeliang/dev/code/python/TikTokDownload/Util/Profile.py", line 88, in re_match
    async with session.get(url=Util.reFind(inputs),
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/aiohttp/client.py", line 1141, in __aenter__
    self._resp = await self._coro
                 ^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/aiohttp/client.py", line 536, in _request
    conn = await self._connector.connect(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/aiohttp/connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/aiohttp/connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/aiohttp/connector.py", line 1209, in _create_direct_connection
    raise last_exc
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/aiohttp/connector.py", line 1178, in _create_direct_connection
    transp, proto = await self._wrap_create_connection(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/aiohttp/connector.py", line 982, in _wrap_create_connection
    raise ClientConnectorCertificateError(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorCertificateError: Cannot connect to host www.douyin.com:443 ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1002)')]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/youzeliang/dev/code/python/TikTokDownload/Util/Profile.py", line 450, in get_Profile
    self.sec_user_id = await self.get_all_sec_user_id(inputs=self.config['uid'])
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/youzeliang/dev/code/python/TikTokDownload/Util/Profile.py", line 166, in get_all_sec_user_id
    raise RuntimeError(f"网络连接异常，异常：{e}")
RuntimeError: 网络连接异常，异常：Cannot connect to host www.douyin.com:443 ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1002)')]

**Comment by Johnserf-Seed** [comment]
请按照模板提供关键信息，你这个情况很明显是你本地网络问题，我不知道你是否开启了代理，如有请关闭。非项目代码，依赖问题均可在百度找到。

**Comment by yanhan918** [comment]
解决了吗，我也是一样的报错。MacOS13.4，Python3.11.5

**Comment by lushangshu** [comment]
把请求的ssl关闭即可，
如下代码：
 connector = Util.aiohttp.TCPConnector(limit=int(self.config['max_connections']),ssl=False)
async with Util.aiohttp.ClientSession(connector=aiohttp.TCPConnector(ssl=False)) as session:

关键的就是 ssl = False

**Comment by yuanliangYL** [comment]
> 解决了吗，我也是一样的报错。MacOS13.4，Python3.11.5

同样问题+1，又解决方案吗？

**Comment by Johnserf-Seed** [comment]
> > 解决了吗，我也是一样的报错。MacOS13.4，Python3.11.5
> 
> 同样问题+1，又解决方案吗？

网络问题，和运营商劫持有关，问题随缘消失
