### ISSUE TITLE
GUI 运行抓取时会出现以下报错信息

### ISSUE THREAD

**Issue by a943512** [Johnserf-Seed/TikTokDownload#539]
[   💻   ]:Windows平台
Traceback (most recent call last):
  File "h:\Code\TikTokDownload-main\TikTokMultiGUI.py", line 47, in run
    args = Util.Command().setting()
           ^^^^^^^^^^^^^^
  File "h:\Code\TikTokDownload-main\Util\Command.py", line 32, in __init__
    self.setting()
  File "h:\Code\TikTokDownload-main\Util\Command.py", line 81, in setting
    cfg = Util.Config().check()
          ^^^^^^^^^^^^^^^^^^^^^
  File "h:\Code\TikTokDownload-main\Util\Config.py", line 129, in check
    Util.Updata(self.cf['update'])
  File "h:\Code\TikTokDownload-main\TikTokUpdata.py", line 47, in __init__
    self.console.print('[   ??   ]:更新已被禁止')
  File "D:\InstallFile\Python11\Lib\site-packages\rich\console.py", line 1672, in print
    with self:
  File "D:\InstallFile\Python11\Lib\site-packages\rich\console.py", line 864, in __exit__
    self._exit_buffer()
  File "D:\InstallFile\Python11\Lib\site-packages\rich\console.py", line 822, in _exit_buffer
    self._check_buffer()
  File "D:\InstallFile\Python11\Lib\site-packages\rich\console.py", line 2064, in _check_buffer
    self.file.flush()
    ^^^^^^^^^^^^^^^
AttributeError: 'Signal' object has no attribute 'flush'

**Comment by Johnserf-Seed** [comment]
GUI在新版已经废弃了，以后会用C#重新写
