### ISSUE TITLE
[BUG]接口返回异常

### ISSUE THREAD

**Issue by QiQi777iii** [Johnserf-Seed/TikTokDownload#546]
**描述出现的错误**
我是自己的填写的cooike，配置文件是完好的
但是出现了借口异常

**bug复现**
错误代码如下
异常，接口内容返回异常: status_code=2，Traceback (most recent call last):
  File "P:\下载\TikTokDownload-main\TikTokDownload-main\Util\Profile.py", line 453, in get_Profile
    user_profile_info = await self.get_user_profile_info(self.headers, self.sec_user_id)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "P:\下载\TikTokDownload-main\TikTokDownload-main\Util\Profile.py", line 315, in get_user_profile_info
    raise RuntimeError(f"接口内容返回异常: status_code={info_status_code}")
RuntimeError: 接口内容返回异常: status_code=2

**Comment by tywilsonsky** [comment]
删掉Cookie，再重新扫码就ok了
