### ISSUE TITLE
[BUG] Traceback (most recent call last): File "TikTokTool.py", line 23

### ISSUE THREAD

**Issue by HarlockHomes** [Johnserf-Seed/TikTokDownload#558]
**描述出现的错误**
[   💻   ]:Windows平台
Traceback (most recent call last):
  File "TikTokTool.py", line 23, in <module>

  File "Util\Command.py", line 32, in __init__
    Returns:
    ^^^^^^^^^
  File "Util\Command.py", line 81, in setting
    Util.log.info('[  提示  ]:读取命令完成!')
      ^^^^^^^^^^^^^^^^^^
  File "Util\Config.py", line 126, in check
  File "Util\Config.py", line 188, in validate_config
AttributeError: 'Section' object has no attribute 'startswith'
[30800] Failed to execute script 'TikTokTool' due to unhandled exception!

**bug复现**
cmd中输入 tiktoktool 回车

**截图**
如果适用，添加屏幕截图以帮助解释您的问题。

**桌面（请填写以下信息）：**
-操作系统：windows 11
-vpn代理：无
-项目版本：如1.4.2.2
-py版本：3.11.1
-依赖库的版本：[出错的库版本号]

**附文**
询问解决办法。

**Comment by HarlockHomes** [comment]
Windows Terminal 的事，server 2016 里没有微软商店，怎么办？

**Comment by Johnserf-Seed** [comment]
去官网下载最新安装包https://github.com/microsoft/terminal/releases
在ps里用Add-AppxPackage命令安装

**Comment by HarlockHomes** [comment]
> 去下载最新安装包https://github.com/microsoft/terminal/releases 在ps里用Add-AppxPackage命令安装

PS C:\Users\Administrator\downloads> Add-AppxPackage .\wt.msixbundle
Add-AppxPackage : 部署失败，原因是 HRESULT: 0x80073CF0, 无法打开包。
错误 0x8007007B: 从位置 wt.msixbundle 中打开程序包失败。
注: 有关其他信息，请在事件日志中查找 [ActivityId] 550f0225-df80-0001-cda1-4e5680dfd901，或使用命令行 Get-AppxLog -ActivityID 550f0225-df80-0001-cda1-4e5680dfd901
所在位置 行:1 字符: 1
+ Add-AppxPackage .\wt.msixbundle
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OpenError: (C:\Users\Admini...s\wt.msixbundle:String) [Add-AppxPackage], FileNotFoundException
    + FullyQualifiedErrorId : DeploymentError,Microsoft.Windows.Appx.PackageManager.Commands.AddAppxPackageCommand

PS C:\Users\Administrator\downloads>
