### ISSUE TITLE
请问 -I 命令参数 应该怎么写？

### ISSUE THREAD

**Issue by HarlockHomes** [Johnserf-Seed/TikTokDownload#561]
PS G:\tiktok> .\tiktoktool -I 2019-11-20|2019-12-01
所在位置 行:1 字符: 28
+ .\tiktoktool -I 2019-11-20|2019-12-01
+                            ~~~~~~~~~~
只允许将表达式作为管道的第一个元素。
    + CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : ExpressionsMustBeFirstInPipeline

PS G:\tiktok> .\tiktoktool -I 2019-11-11|2019-12-11
所在位置 行:1 字符: 28
+ .\tiktoktool -I 2019-11-11|2019-12-11
+                            ~~~~~~~~~~
只允许将表达式作为管道的第一个元素。
    + CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : ExpressionsMustBeFirstInPipeline

PS G:\tiktok> .\tiktoktool -I 2019-11-11|2019-12-12
所在位置 行:1 字符: 28
+ .\tiktoktool -I 2019-11-11|2019-12-12
+                            ~~~~~~~~~~
只允许将表达式作为管道的第一个元素。
    + CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
    

**桌面（请填写以下信息）：**
-操作系统：[windows11 64bit]
-vpn代理：[关闭]
-项目版本：[1.4.2.2]
-py版本：[3.11.1]
-依赖库的版本：[出错的库版本号]

**Comment by Johnserf-Seed** [comment]
字符串的参数都要用单引号''包围起来

**Comment by HarlockHomes** [comment]
PS G:\tiktok> .\tiktoktool -I '2023-03-01|2023-04-01'


[  提示  ]:异常，输入参数必须是字符串或列表。
[2023-09-28 17:13:04,571] - Log.py] - ERROR: [  提示  ]:异常，输入参数必须是字符串或列表。，Traceback (most recent call last):
  File "Util\Profile.py", line 450, in get_Profile
    self.sec_user_id = await self.get_all_sec_user_id(inputs=self.config['uid'])
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "Util\Profile.py", line 154, in get_all_sec_user_id
    raise TypeError("输入参数必须是字符串或列表。")
TypeError: 输入参数必须是字符串或列表。

[  提示  ]：按任意键退出程序!



> 字符串的参数都要用单引号''包围起来
