### ISSUE TITLE
【使用】我想问下。这个在linux命令行下（debian）怎么使用

### ISSUE THREAD

**Issue by Whichbfj28** [Johnserf-Seed/TikTokDownload#565]
教程好像说的都是windows如何使用。但是我觉得这种会经常更新视频的东西。使用debian进行定时增量更新是更好的选择
但是不知道在debian下。这个程序应该怎么使用

**Comment by Johnserf-Seed** [comment]
用命令行加任务计划即可

**Comment by Whichbfj28** [comment]
> 用命令行加任务计划即可

命令行加任务计划我会
关键是我不知道要执行什么命令。
运行：TikTokTool.py -u https://v.douyin.com/*** 弹出

```
import Util

if __name__ == '__main__':
    # 获取命令行和配置文件
    cmd = Util.Command()
    config = cmd.config_dict
    dyheaders = cmd.dyheaders

    # 异步下载作品
    Util.asyncio.run(Util.Profile(config, dyheaders).get_Profile())
    input("[  提示  ]:下载完成，输入任意键退出。")
```

**Comment by Johnserf-Seed** [comment]
> > 用命令行加任务计划即可
> 
> 命令行加任务计划我会 关键是我不知道要执行什么命令。 运行：TikTokTool.py -u https://v.douyin.com/*** 弹出
> 
> ```
> import Util
> 
> if __name__ == '__main__':
>     # 获取命令行和配置文件
>     cmd = Util.Command()
>     config = cmd.config_dict
>     dyheaders = cmd.dyheaders
> 
>     # 异步下载作品
>     Util.asyncio.run(Util.Profile(config, dyheaders).get_Profile())
>     input("[  提示  ]:下载完成，输入任意键退出。")
> ```

命令行需要完整的按照配置文件来

**Comment by Whichbfj28** [comment]
> > > 用命令行加任务计划即可
> > 
> > 
> > 命令行加任务计划我会 关键是我不知道要执行什么命令。 运行：TikTokTool.py -u https://v.douyin.com/*** 弹出
> > ```
> > import Util
> > 
> > if __name__ == '__main__':
> >     # 获取命令行和配置文件
> >     cmd = Util.Command()
> >     config = cmd.config_dict
> >     dyheaders = cmd.dyheaders
> > 
> >     # 异步下载作品
> >     Util.asyncio.run(Util.Profile(config, dyheaders).get_Profile())
> >     input("[  提示  ]:下载完成，输入任意键退出。")
> > ```
> 
> 命令行需要完整的按照配置文件来

没看懂。完整的按照配置文件是什么意思。
配置好conf.ini文件。还是说把全部参数写到命令里面去。

**Comment by Johnserf-Seed** [comment]
> > > > 用命令行加任务计划即可
> > > 
> > > 
> > > 命令行加任务计划我会 关键是我不知道要执行什么命令。 运行：TikTokTool.py -u https://v.douyin.com/*** 弹出
> > > ```
> > > import Util
> > > 
> > > if __name__ == '__main__':
> > >     # 获取命令行和配置文件
> > >     cmd = Util.Command()
> > >     config = cmd.config_dict
> > >     dyheaders = cmd.dyheaders
> > > 
> > >     # 异步下载作品
> > >     Util.asyncio.run(Util.Profile(config, dyheaders).get_Profile())
> > >     input("[  提示  ]:下载完成，输入任意键退出。")
> > > ```
> > 
> > 
> > 命令行需要完整的按照配置文件来
> 
> 没看懂。完整的按照配置文件是什么意思。 配置好conf.ini文件。还是说把全部参数写到命令里面去。

![image](https://github.com/Johnserf-Seed/TikTokDownload/assets/40727745/7a649ad6-4362-40f8-a2c3-2517e5a18287)

**Comment by Whichbfj28** [comment]
TikTokTool.py --uid https://v.douyin.com/***/ --cover yes --desc yes --folderize yes --mode post --name {create}_{desc} --cookie  --update yes --limit all --max_connections  5 --max_tasks   5
依然弹出

```

#!/usr/bin/env python
# -*- encoding: utf-8 -*-
'''
@Description:V1.py
@Date       :2022/07/29 23:19:14
@Author     :JohnserfSeed
@version    :1.0
@License    :MIT License
@Github     :https://github.com/johnserf-seed
@Mail       :johnserfseed@gmail.com
-------------------------------------------------
Change Log  :
2022/07/29 23:19:14 : Init
2023/03/10 16:22:19 : gen dyheaders
2023/08/04 02:09:31 : async download
-------------------------------------------------
'''

import Util

if __name__ == '__main__':
    # 获取命令行和配置文件
    cmd = Util.Command()
    config = cmd.config_dict
    dyheaders = cmd.dyheaders

    # 异步下载作品
    Util.asyncio.run(Util.Profile(config, dyheaders).get_Profile())
    input("[  提示  ]:下载完成，输入任意键退出。")
```

不知道作者是否有空的时候写个专门的linux程？

**Comment by cws999** [comment]
我会，下载过多次了。感谢作者，感谢所有的开发人员
切换到程序目录
python3 -m venv venv
source ./venv/bin/activate
pip install -r requirements.txt
配置conf.ini
开始下载了
python3 ./TikTokTool.py -u https://www.douyin.com/user/XXXXXXXXXXXXXXXXXXXX  --max_connections=6 --max_tasks=5 --folderize=no --update=no --naming={create}_{id}
完成



####################################
想问一下出现以下这些错误代码怎么办
`[  视频  ]:2023-06-24 00.31.01_7247919839761714471_video.mp4                 ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━         100.0%   •  1.3/1.3 MB        •  8.8 MB/s     •  0:00:00
[  提示  ]:抓获1687537861000页数据成功! 该页共18个作品。
[  提示  ]:异常，运行异常, 异常: 
[2023-10-04 20:30:43,978] - Log.py] - ERROR: [  提示  ]:异常，运行异常, 异常: ，Traceback (most recent call last):
  File "/TikTokDownload/Util/Profile.py", line 341, in get_user_post_info
    aweme_list, max_cursor, has_more = await self.get_request_data('GET', url, headers)
                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/TikTokDownload/Util/Profile.py", line 120, in get_request_data
    async with session.request(method, url, headers=headers, data=data, timeout=10) as response:
  File "/TikTokDownload/venv/lib/python3.11/site-packages/aiohttp/client.py", line 1141, in __aenter__
    self._resp = await self._coro
                 ^^^^^^^^^^^^^^^^
  File "/TikTokDownload/venv/lib/python3.11/site-packages/aiohttp/client.py", line 560, in _request
    await resp.start(conn)
  File "/TikTokDownload/venv/lib/python3.11/site-packages/aiohttp/client_reqrep.py", line 894, in start
    with self._timer:
  File "/TikTokDownload/venv/lib/python3.11/site-packages/aiohttp/helpers.py", line 721, in __exit__
    raise asyncio.TimeoutError from None
TimeoutError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/TikTokDownload/Util/Profile.py", line 503, in get_Profile
    aweme_data = await self.get_user_post_info(self.headers, self.profile_URL)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/TikTokDownload/Util/Profile.py", line 348, in get_user_post_info
    raise RuntimeError(f"运行异常, 异常: {e}") from e
RuntimeError: 运行异常, 异常: 

(venv) xxx@xxx TikTokDownload `

**Comment by ttlttc** [comment]
debian按楼上方法运行到pip install -r requirements.txt这一步安装不成功,提示版本找不到?
已经运行pip install --upgrade pip

手动改了低版本装上也跑不起来

 3.33.1, 3.34.0)
No matching distribution found for gradio==3.39.0 (from -r requirements.txt (line 4))


 9.4.0, 9.5.0)
No matching distribution found for Pillow==10.0.0 (from -r requirements.txt (line 6))

**Comment by Johnserf-Seed** [comment]
> debian按楼上方法运行到pip install -r requirements.txt这一步安装不成功,提示版本找不到? 已经运行pip install --upgrade pip
> 
> 手动改了低版本装上也跑不起来
> 
> 3.33.1, 3.34.0) No matching distribution found for gradio==3.39.0 (from -r requirements.txt (line 4))
> 
> 9.4.0, 9.5.0) No matching distribution found for Pillow==10.0.0 (from -r requirements.txt (line 6))

那你可以设置一下pip的镜像，或者指定某个镜像地址

**Comment by ttlttc** [comment]
发现问题是debian11的py3版本只有3.9,系统重装了debian12就可以了,感谢各位
