### ISSUE TITLE
[BUG]json.decoder.JSONDecodeError:

### ISSUE THREAD

**Issue by boluohong** [Johnserf-Seed/TikTokDownload#570]
从10月5日中午开始出现
json.decoder.JSONDecodeError:
大概是抖音有修改了什么

[   💻   ]:Windows平台
[  提示  ]:读取命令完成!
[  提示  ]:读取命令完成!
[  提示  ]:批量获取所有视频中!
[  提示  ]:用户的sec_id=MS4wLjABAAAATsF_wTB-6vFFjc2IoKmQ3lZaDhoH6pkOI54TRWb_9zo
[  提示  ]:正在进行第 1 次尝试
[  用户  ]:小肥猪babe
[  提示  ]:抓获用户主页数据成功!
[  提示  ]:正在替换当页所有作品非法字符，耐心等待!

[  提示  ]:正在对 1692525245000 页进行第 1 次尝试！
[  提示  ]:第 1688206188000 页抓获数据成功!
[  提示  ]:正在替换当页所有作品非法字符，耐心等待!
[  提示  ]:正在替换作者非法字符，耐心等待!
Traceback (most recent call last):
  File "1.py", line 32, in <module>
    profile.getProfile(cmd.setting())
  File "T:\0311\Util\Profile.py", line 132, in getProfile
    self.getData(self.api_post_url)
  File "T:\0311\Util\Profile.py", line 182, in getData
    self.getVideoInfo(result)
  File "T:\0311\Util\Profile.py", line 303, in getVideoInfo
    self.getNextData()
  File "T:\0311\Util\Profile.py", line 233, in getNextData
    self.getVideoInfo(result)
  File "T:\0311\Util\Profile.py", line 300, in getVideoInfo
    datas = Util.Images(self.headers).get_all_images(self.image_list)
  File "T:\0311\Util\Images.py", line 56, in get_all_images
    js = Util.json.loads(r)
  File "C:\Users\hp\AppData\Local\Programs\Python\Python37\lib\json\__init__.py
, line 348, in loads
    return _default_decoder.decode(s)
  File "C:\Users\hp\AppData\Local\Programs\Python\Python37\lib\json\decoder.py"
 line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\hp\AppData\Local\Programs\Python\Python37\lib\json\decoder.py"
 line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by Johnserf-Seed** [comment]
更新cookie再试试

**Comment by boluohong** [comment]
> 更新cookie再试试

这是老版本（也就是cookie是手动填入）
昨天傍晚时分它提示没有cookie，我手动登录填了一个新的，但是当时仍然无法下载
等到今天早上又可以了
总之谢谢作者，这个老版本能用到哪天就算哪天吧
