### ISSUE TITLE
[BUG]新版本出现SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by boluohong** [Johnserf-Seed/TikTokDownload#571]
之前用的不是最新版本，昨天突然出现json.decoder解码问题
想着用用新版本能不能行
结果如下
Traceback (most recent call last):
  File "1.py", line 19, in <module>
    import Util
  File "T:\1005\Util\__init__.py", line 44, in <module>
    import aiohttp
  File "C:\Users\hp\AppData\Local\Programs\Python\Python37\lib\site-packages\aio
http\__init__.py", line 11, in <module>
    from .connector import *  # noqa
  File "C:\Users\hp\AppData\Local\Programs\Python\Python37\lib\site-packages\aio
http\connector.py", line 16, in <module>
    from . import hdrs, helpers
  File "C:\Users\hp\AppData\Local\Programs\Python\Python37\lib\site-packages\aio
http\helpers.py", line 30
    ensure_future = asyncio.async
                                ^
SyntaxError: invalid syntax

**Comment by Johnserf-Seed** [comment]
1.py的内容是什么？ 你这个是代码语法错误

**Comment by akafanfan** [comment]
检查 python 版本 相关代码不同版本 python  可能不支持

**Comment by boluohong** [comment]
大概率是因为python版本低导致的，没办法老电脑用的是win7
在此也提提一个意见
新版本固然很好，但是一些比较老的电脑还有用win7的用不了
希望作者以后将这个因素也考虑在内

**Comment by Johnserf-Seed** [comment]
> 大概率是因为python版本低导致的，没办法老电脑用的是win7 在此也提提一个意见 新版本固然很好，但是一些比较老的电脑还有用win7的用不了 希望作者以后将这个因素也考虑在内

win7已经停止支持了，还是建议升级系统的。因为新版的py有更多的特性，关键是一些库最低不支持那些老版本
