### ISSUE TITLE
[BUG] 抖音协议是不是修改了，扫描成功了没反应；老cookie无法使用也报错

### ISSUE THREAD

**Issue by 253627764** [Johnserf-Seed/TikTokDownload#605]
问题1：从今天（2023年11月25日18:04:19）开始，测试发现。扫描成功之后没反应，卡在不动了
      [  登录  ]:请扫描登录二维码。
      [  登录  ]:等待二维码扫描！
      [  登录  ]:等待二维码扫描！
      [  登录  ]:等待二维码扫描！
      [  登录  ]:扫描二维码成功！

问题2：老cookie版本也报错，大概是json解析失败
[   💻   ]:Windows平台
[   🗻   ]:获取最新版本号中!
[   🚩   ]:目前 14200 版本已是最新
[  配置  ]:配置验证成功!
[  配置  ]:获取命令行完成!
[  提示  ]:异常，本地网络请求异常。 异常: 0, message='Attempt to decode JSON with unexpected mimetype: text/plain; charset=utf-8',

Traceback (most recent call last):
  File "Util\Profile.py", line 461, in get_Profile
    user_profile_info = await self.get_user_profile_info(self.headers, self.sec_user_id)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "Util\Profile.py", line 321, in get_user_profile_info
    raise RuntimeError(f"本地网络请求异常。 异常: {e}\r") from e
RuntimeError: 本地网络请求异常。 异常: 0, message='Attempt to decode JSON with unexpected mimetype: text/plain; charset=utf-8', 

[  提示  ]：按任意键退出程序!

**Comment by 475333676** [comment]
我也遇到了同样的问题，请问如何解决

**Comment by 253627764** [comment]
> 我也遇到了同样的问题，请问如何解决

我刚刚试了，只要修改cookie就可以了、把浏览器中的 cookie值复制到 conf.ini 中就可以了；但是扫描我没看，我是直接复制的，等作者大佬修改吧。我先手工修改了

**Comment by 253627764** [comment]
> 我也遇到了同样的问题，请问如何解决

Cookie的获得位置，Chrome最新版本浏览器
![微信截图_20231125190254](https://github.com/Johnserf-Seed/TikTokDownload/assets/2902735/f8ceb460-8d70-4486-a458-c5ea6cb96640)

**Comment by 253627764** [comment]
> 我也遇到了同样的问题，请问如何解决

不好意思，解决方案，刚刚删除了，我刚发完解决方法就不行了，协议又改了；估计是被盯上了；所以我删除了；等作者的终极方案吧

**Comment by HarlockHomes** [comment]
看来确实出故障了

**Comment by edgleaf** [comment]
同样的问题，扫描成功没反应

**Comment by JoeanAmier** [comment]
感觉不是失效，而是风控严了。

**Comment by xyslsg** [comment]
确实，扫了码一直停在那不动

**Comment by sldtt** [comment]
同样的问题QAQ
更换了账号后也无法去使用:(

**Comment by sldtt** [comment]
> 同样的问题QAQ 更换了账号后也无法去使用:(

刚刚成功实现了爬取。打开抖音自己的主页后，按F12进入开发者模式，选择Network的那一栏，之后刷新界面。点击network栏中左边的第一个名称，在他的Headers中往下寻找可以找到cookie。将这个cookie复制到我们的脚本文件中即可运行。

**Comment by qq517739813** [comment]
> > 同样的问题QAQ 更换了账号后也无法去使用:(
> 
> 刚刚成功实现了爬取。打开抖音自己的主页后，按F12进入开发者模式，选择Network的那一栏，之后刷新界面。点击network栏中左边的第一个名称，在他的Headers中往下寻找可以找到cookie。将这个cookie复制到我们的脚本文件中即可运行。

好兄弟是哪个请求名称呢，是browser开头的那个吗

**Comment by ggwfnh** [comment]
> > 同样的问题QAQ更换了账号后也无法去使用:(
> 
> 刚刚成功实现了爬取。打开抖音自己的主页后，按F12进入开发者模式，选择网络的那一栏，之后刷新界面。点击网络左边的第一个名称，在他的Headers中往里接下来寻找可以找到cookie。将这个cookie复制到我们的脚本文件中就可以运行了。

能不能再说细一点，那个网络左边第一个名称，就不知道是哪 个了，在哪点找、

**Comment by sldtt** [comment]
![1a93e4c8d08e98f168ca1823e4003f3](https://github.com/Johnserf-Seed/TikTokDownload/assets/106641688/df1724a2-e8e4-42aa-b75e-e1d23f9a5798)
如图，可以在自己的主页试。应该cookie都是一样的

**Comment by sldtt** [comment]
> > > 同样的问题QAQ 更换了账号后也无法去使用:(
> > 
> > 
> > 刚刚成功实现了爬取。打开抖音自己的主页后，按F12进入开发者模式，选择Network的那一栏，之后刷新界面。点击network栏中左边的第一个名称，在他的Headers中往下寻找可以找到cookie。将这个cookie复制到我们的脚本文件中即可运行。
> 
> 好兄弟是哪个请求名称呢，是browser开头的那个吗

发到下面了好兄弟，你可以看一下

**Comment by sldtt** [comment]
> > > 同样的问题QAQ更换了账号后也无法去使用:(
> > 
> > 
> > 刚刚成功实现了爬取。打开抖音自己的主页后，按F12进入开发者模式，选择网络的那一栏，之后刷新界面。点击网络左边的第一个名称，在他的Headers中往里接下来寻找可以找到cookie。将这个cookie复制到我们的脚本文件中就可以运行了。
> 
> 能不能再说细一点，那个网络左边第一个名称，就不知道是哪 个了，在哪点找、

发到下面了好兄弟，你可以看一下

**Comment by puguojingm** [comment]
![image](https://github.com/Johnserf-Seed/TikTokDownload/assets/16621280/2c2aae85-7b0c-4ed2-a4b9-b05eb8e2b09e)

**Comment by mingchuanlu** [comment]
谢谢大佬，之前自作聪明就截取了对应的字段，结果报错，直接全部粘贴就好

**Comment by Godmyhave** [comment]
可能是风控，或者参数生成方式该更新了。（ttwid生成的和浏览器复制出来的还是有区别，有时候风控时直接使用复制浏览器的ttwid能成功）
我这边是一阵一阵的。
![image](https://github.com/Johnserf-Seed/TikTokDownload/assets/59076131/fb4e7ba2-4684-4f2b-9706-2c11cfed9387)

**Comment by iamyuanzhuyu** [comment]
我也是扫描登陆了没反应

**Comment by hold88888888** [comment]
请教一下cookie应该放在哪里？
![屏幕截图 2023-12-25 143515](https://github.com/Johnserf-Seed/TikTokDownload/assets/105548184/1d513471-a8be-454b-950e-3e009c3b4b4a)

**Comment by sldtt** [comment]
你好，conf文件中应该会有相应字段的，你查看一下


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Johnserf-Seed/TikTokDownload"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年12月25日(星期一) 下午2:37
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Johnserf-Seed/TikTokDownload] [BUG] 抖音协议是不是修改了，扫描成功了没反应；老cookie无法使用也报错 (Issue #605)





 
请教一下cookie应该放在哪里？
 2023-12-25.143515.png (view on web)

**Comment by hold88888888** [comment]
> 你好，conf文件中应该会有相应字段的，你查看一下
> 
> 
> ------------------&nbsp;原始邮件&nbsp;------------------
> 发件人:                                                                                                                        "Johnserf-Seed/TikTokDownload"                                                                                    ***@***.***&gt;;
> 发送时间:&nbsp;2023年12月25日(星期一) 下午2:37
> ***@***.***&gt;;
> ***@***.******@***.***&gt;;
> 主题:&nbsp;Re: [Johnserf-Seed/TikTokDownload] [BUG] 抖音协议是不是修改了，扫描成功了没反应；老cookie无法使用也报错 (Issue #605)
> 
> 
> 
> 
> 
>  
> 请教一下cookie应该放在哪里？
>  2023-12-25.143515.png (view on web)
>  
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you commented.Message ID: ***@***.***&gt;

感谢😊！解决了(￣▽￣)～■干杯

**Comment by xiao-keeplearning** [comment]
为什么有时候可以下载，有时候网络请求异常不可以下载。是cookie被风控了么

**Comment by lululutx** [comment]
没下载就退出了...
