### ISSUE TITLE
[BUG]exe文件与f2好像都有问题

### ISSUE THREAD

**Issue by chensimmons** [Johnserf-Seed/TikTokDownload#624]
第一次使用这个软件，
1.5版本，使用exe文件，提示应用配置路径不存在，报错信息：

Traceback (most recent call last):
  File "TikTokTool.py", line 40, in <module>
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 385, in exec_module
  File "f2\apps\douyin\cli.py", line 17, in <module>
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 385, in exec_module
  File "f2\apps\douyin\handler.py", line 11, in <module>
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 385, in exec_module
  File "f2\apps\douyin\crawler.py", line 10, in <module>
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 385, in exec_module
  File "f2\apps\douyin\model.py", line 6, in <module>
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 385, in exec_module
  File "f2\apps\douyin\utils.py", line 36, in <module>
  File "f2\apps\douyin\utils.py", line 37, in TokenManager
  File "f2\utils\conf_manager.py", line 26, in __init__
  File "f2\utils\conf_manager.py", line 38, in load_config
NameError: name 'exit' is not defined
[3724] Failed to execute script 'TikTokTool' due to unhandled exception!

另外，f2无法初始化配置文件
<img width="745" alt="003" src="https://github.com/Johnserf-Seed/TikTokDownload/assets/31755429/a11517a5-0667-4423-acea-ed42d563cdf6">
`

**Comment by Johnserf-Seed** [comment]
再刚刚的issue已经修复了，https://github.com/Johnserf-Seed/TikTokDownload/issues/623  PR https://github.com/Johnserf-Seed/f2/pull/15
现在还没有推送到pypi，可以在releases下载最新whl包本地安装 https://github.com/Johnserf-Seed/f2/releases/tag/v0.0.1-pw1

**Comment by Johnserf-Seed** [comment]
等待国内镜像站同步再升级 ，或使用官方镜像立即升级。
```bash
pip install --upgrade f2 -i https://pypi.org/simple
```

**Comment by zaneyew** [comment]
Meet the same error, only help information while configured as instructed.

**Comment by Johnserf-Seed** [comment]
由于打包的问题，TikTokTool不再打包了，直接使用TikTokTool.py即可。

**Comment by Johnserf-Seed** [comment]
请更新至v0.0.1.2版本 https://github.com/Johnserf-Seed/f2/releases/tag/v0.0.1.2
```bash
pip install --upgrade f2
```

**Comment by Johnserf-Seed** [comment]
https://github.com/Johnserf-Seed/f2/pull/39
