### ISSUE TITLE
安装 f2 遇到的问题 

### ISSUE THREAD

**Issue by ZaiKL** [Johnserf-Seed/TikTokDownload#641]
**描述出现的错误** 
  Using cached pytest-7.4.2-py3-none-any.whl.metadata (7.9 kB)
Collecting pyyaml==6.0 (from f2)
  Using cached PyYAML-6.0.tar.gz (124 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [54 lines of output]
      running egg_info
      writing lib\PyYAML.egg-info\PKG-INFO
      writing dependency_links to lib\PyYAML.egg-info\dependency_links.txt
      writing top-level names to lib\PyYAML.egg-info\top_level.txt
      Traceback (most recent call last):
        File "C:\Users\kaikoliang\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "C:\Users\kaikoliang\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
（直接安装可以成功  
pip install PyYAML
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: PyYAML in c:\users\kaikoliang\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (6.0.1)）
**bug复现**
复现这次行为的步骤：
  pip install  f2

**截图**
如果适用，添加屏幕截图以帮助解释您的问题。
![图片](https://github.com/Johnserf-Seed/TikTokDownload/assets/86660941/79c243a4-1227-4ee4-8687-8175485e6b10)

**桌面（请填写以下信息）：**
-操作系统：[windows11 64bit]
-vpn代理：[关闭]
-项目版本：[15000]
-py版本：[Python 3.12.1]
-依赖库的版本：[ PyYAML-6.0.tar.gz]

**附文**
在此处添加有关此问题的其他备注。

**Comment by JoeanAmier** [comment]
俺也一样。

**Comment by PolarisDust** [comment]
用3.11.1

**Comment by AndersonBY** [comment]
3.12可以把项目依赖里的pyyaml改到6.0.1就可以安装了

**Comment by HogwartsRico** [comment]
我也出现了这个问题

**Comment by Johnserf-Seed** [comment]
因为pyyaml6.0版本不兼容py3.12版本 https://github.com/yaml/pyyaml/issues/736

**Comment by quan8tum** [comment]
同款问题，用pip install pyyaml==6.0.1 f2 --no-deps虽然安装完成了，但
$ python TikTokTool.py -h
Traceback (most recent call last):
  File "D:\Apps\TikTokDownload-main\TikTokTool.py", line 40, in <module>
    from f2.apps.douyin.cli import douyin
  File "D:\Apps\TikTokDownload-main\f2\apps\douyin\cli.py", line 4, in <module>
    import click
ModuleNotFoundError: No module named 'click'

**Comment by jobsguo** [comment]
pip install pyyaml==6.0.1 f2 --no-deps   这个真是靠谱，搞了好久才找到这个命令。
然后再看缺少哪个module，就安装就好了，会有好多个要再次安装的
譬如：pip install click
======================================
基本上他提示的这些都要全部安装：
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
f2 0.0.1.3 requires jsonpath-ng==1.6.0, which is not installed.
f2 0.0.1.3 requires pytest==7.4.2, which is not installed.
f2 0.0.1.3 requires pytest-asyncio==0.21.1, which is not installed.
atible.
f2 0.0.1.3 requires httpx==0.25.0, but you have httpx 0.26.0 which is incompatible.
f2 0.0.1.3 requires importlib-resources==6.1.0, but you have importlib-resources 6.1.1 which is incompatible.
f2 0.0.1.3 requires m3u8==3.6.0, but you have m3u8 4.0.0 which is incompatible.
f2 0.0.1.3 requires pydantic==1.10.12, but you have pydantic 2.6.0 which is incompatible.
f2 0.0.1.3 requires pyyaml==6.0, but you have pyyaml 6.0.1 which is incompatible.
f2 0.0.1.3 requires rich==13.6.0, but you have rich 13.7.0 which is incompatible.
![图片](https://github.com/Johnserf-Seed/TikTokDownload/assets/1125139/486c79b9-2906-4884-9270-8e9d2b530d90)

**Comment by iamgaoxing** [comment]
https://github.com/Johnserf-Seed/TikTokDownload/issues/641#issuecomment-1925560568
跟着这位兄弟的回答走了一遍，在安装那些缺失包的时候，又出现了兼容问题，我的解决办法是不要安装最新的 python 版本，安装 f2 支持的不那么新的 python 版本。
