### ISSUE TITLE
ValueError: Unknown scheme for proxy URL URL('nulls')

### ISSUE THREAD

**Issue by navyNIE** [Johnserf-Seed/TikTokDownload#648]
开始能下载，后面下载就一直报错如下：

PS E:\Crawler\f2-main> f2 dy -c dy.yaml
INFO     App: douyin
INFO     主配置： conf/app.yaml
INFO     自定义配置： dy.yaml

Traceback (most recent call last):
  File "D:\Software\anaconda3\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "D:\Software\anaconda3\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "D:\Software\anaconda3\Scripts\f2.exe\__main__.py", line 7, in <module>
  File "D:\Software\anaconda3\lib\site-packages\click\core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "D:\Software\anaconda3\lib\site-packages\click\core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "D:\Software\anaconda3\lib\site-packages\click\core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "D:\Software\anaconda3\lib\site-packages\click\core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "D:\Software\anaconda3\lib\site-packages\click\core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "D:\Software\anaconda3\lib\site-packages\click\decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "D:\Software\anaconda3\lib\site-packages\f2\apps\douyin\cli.py", line 429, in douyin
    ctx.invoke(set_cli_config, **kwargs)
  File "D:\Software\anaconda3\lib\site-packages\click\core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "D:\Software\anaconda3\lib\site-packages\click\decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "D:\Software\anaconda3\lib\site-packages\f2\cli\cli_commands.py", line 134, in set_cli_config
    asyncio.run(run_app(kwargs))
  File "D:\Software\anaconda3\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "D:\Software\anaconda3\lib\asyncio\base_events.py", line 647, in run_until_complete
    return future.result()
  File "D:\Software\anaconda3\lib\site-packages\f2\cli\cli_commands.py", line 142, in run_app
    await app_module.main(kwargs)
  File "D:\Software\anaconda3\lib\site-packages\f2\apps\douyin\handler.py", line 862, in main
    downloader = DouyinDownloader(kwargs)
  File "D:\Software\anaconda3\lib\site-packages\f2\apps\douyin\dl.py", line 25, in __init__
    super().__init__(kwargs)
  File "D:\Software\anaconda3\lib\site-packages\f2\dl\base_downloader.py", line 42, in __init__
    super().__init__(proxies=proxies, crawler_headers=self.headers)
  File "D:\Software\anaconda3\lib\site-packages\f2\crawlers\base_crawler.py", line 71, in __init__
    self.aclient = httpx.AsyncClient(
  File "D:\Software\anaconda3\lib\site-packages\httpx\_client.py", line 1395, in __init__
    proxy_map = self._get_proxy_map(proxies, allow_env_proxies)
  File "D:\Software\anaconda3\lib\site-packages\httpx\_client.py", line 224, in _get_proxy_map
    proxy = Proxy(url=value) if isinstance(value, (str, URL)) else value
  File "D:\Software\anaconda3\lib\site-packages\httpx\_config.py", line 337, in __init__
    raise ValueError(f"Unknown scheme for proxy URL {url!r}")
ValueError: Unknown scheme for proxy URL URL('nulls')

**Comment by Johnserf-Seed** [comment]
请提供一下你的配置文件内容，帮助我判断是不是你代理设置的问题，因为你说开始能下载。
