### ISSUE TITLE
下载一些视频以后会出现的问题

### ISSUE THREAD

**Issue by gkj17** [Johnserf-Seed/TikTokDownload#661]
**描述出现的错误**
遇到bug先在issues中搜索，没有得到解决方案再提交。
对出现bug的地方做清晰而简洁的描述。

**bug复现**
复现这次行为的步骤：
下载【https://www.douyin.com/user/MS4wLjABAAAAfJbYiohY4syKtJ5pCwbCV-KgSFQCnPMUiyRRWjBrdEo】这个主页的视频就会  而且一直都是同一样的报错~

**桌面（请填写以下信息）：**
-操作系统：[windows10 64bit]
-vpn代理：[关闭]
-项目版本：[1.5.0.0]
-py版本：[3.12]
-依赖库的版本：[出错的库版本号]

**附文**

Traceback (most recent call last):
  File "C:\Users\guank\Desktop\TikTokDownload\TikTokTool.py", line 51, in <module>
    clis[int(selected) - 1]()
  File "C:\Users\guank\AppData\Local\Programs\Python\Python312\Lib\site-packages\click\core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\guank\AppData\Local\Programs\Python\Python312\Lib\site-packages\click\core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "C:\Users\guank\AppData\Local\Programs\Python\Python312\Lib\site-packages\click\core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\guank\AppData\Local\Programs\Python\Python312\Lib\site-packages\click\core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\guank\AppData\Local\Programs\Python\Python312\Lib\site-packages\click\decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\guank\AppData\Local\Programs\Python\Python312\Lib\site-packages\f2\apps\douyin\cli.py", line 509, in douyin
    ctx.invoke(set_cli_config, **kwargs)
  File "C:\Users\guank\AppData\Local\Programs\Python\Python312\Lib\site-packages\click\core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\guank\AppData\Local\Programs\Python\Python312\Lib\site-packages\click\decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\guank\AppData\Local\Programs\Python\Python312\Lib\site-packages\f2\cli\cli_commands.py", line 135, in set_cli_config
    asyncio.run(run_app(kwargs))
  File "C:\Users\guank\AppData\Local\Programs\Python\Python312\Lib\asyncio\runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\guank\AppData\Local\Programs\Python\Python312\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\guank\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 664, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\Users\guank\AppData\Local\Programs\Python\Python312\Lib\site-packages\f2\cli\cli_commands.py", line 143, in run_app
    await app_module.main(kwargs)
  File "C:\Users\guank\AppData\Local\Programs\Python\Python312\Lib\site-packages\f2\apps\douyin\handler.py", line 923, in main
    await mode_function_map[mode](DouyinHandler(kwargs))
  File "C:\Users\guank\AppData\Local\Programs\Python\Python312\Lib\site-packages\f2\apps\douyin\handler.py", line 227, in handle_user_post
    await self.downloader.create_download_tasks(
  File "C:\Users\guank\AppData\Local\Programs\Python\Python312\Lib\site-packages\f2\apps\douyin\dl.py", line 141, in create_download_tasks
    await self.execute_tasks()
  File "C:\Users\guank\AppData\Local\Programs\Python\Python312\Lib\site-packages\f2\dl\base_downloader.py", line 451, in execute_tasks
    await asyncio.gather(*self.download_tasks)
  File "C:\Users\guank\AppData\Local\Programs\Python\Python312\Lib\site-packages\f2\dl\base_downloader.py", line 145, in download_file
    async with aiofiles.open(tmp_path, "ab" if start_byte else "wb") as file:
  File "C:\Users\guank\AppData\Local\Programs\Python\Python312\Lib\site-packages\aiofiles\base.py", line 78, in __aenter__
    self._obj = await self._coro
                ^^^^^^^^^^^^^^^^
  File "C:\Users\guank\AppData\Local\Programs\Python\Python312\Lib\site-packages\aiofiles\threadpool\__init__.py", line 80, in _open
    f = yield from loop.run_in_executor(executor, cb)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\guank\AppData\Local\Programs\Python\Python312\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\guank\\Desktop\\TikTokDownload\\Download\\douyin\\post\\李一舟\\2023-10-12 03-16-18_愉快的英国之行_忙里偷闲_来英国玩了一个星期_文武之道_一张一弛_这是我十年创业的经验_绷得太紧_人会失去对机会和危机的判断能力_也会急功近利_错过生活中的美好__读书时候来英国_因为太穷......可能性__互联网可以代替很多体验_但是旅行的真实获得感_是不可取代的__回来以后_马上就双11了_又到了每年最忙的三个月__一起加油_#海外生活_#伦敦_#旅行_#旅行的意义_#带你看世界_image_1.tmp'

**Comment by Johnserf-Seed** [comment]
请将f2更新至`0.0.1.4`

**Comment by gkj17** [comment]
是0.0.1.4
![image](https://github.com/Johnserf-Seed/TikTokDownload/assets/31543062/5c373f0d-531c-4ae4-a4aa-6c32dd82dd26)

**Comment by gkj17** [comment]
我知道了是，是window文件长度导致的：
各位：解决方案：
https://www.autodesk.com.cn/support/technical/article/caas/sfdcarticles/sfdcarticles/CHS/The-Windows-10-default-path-length-limitation-MAX-PATH-is-256-characters.html

**Comment by Johnserf-Seed** [comment]
## 测试还原
![image](https://github.com/Johnserf-Seed/TikTokDownload/assets/40727745/708c79fd-687e-44ab-a916-9ca8f4989d91)

![image](https://github.com/Johnserf-Seed/TikTokDownload/assets/40727745/85d20eb5-05d0-4cb1-b7b3-5eefc8690344)
我本地没有设置长文件名，测试了这个作品是可以正常保存的。这个作品的文件名长度并没有超出我预设Windows环境的220字符长度。

## 问题原因
具体报错是由aiofiles临时文件未找到引起的，具体原因可能为下载的临时文件不存在或目录被删除。

## 其他
`0.0.1.4`版本修复了不同系统环境下的文件名长度问题，但你的报错不是FileNameTooLong错误，是FileNotFound错误。

## 解决方案
使用`f2 -d DEBUG`运行，在输出日志文件中搜索`未下载完的文件`或`临时文件`，检查是否存在该临时目录。删除该作品目录后重新再测试，如果故障依旧需要你提供更详细的信息。
