### ISSUE TITLE
无法下载用户发布视频

### ISSUE THREAD

**Issue by vain-Liang** [Johnserf-Seed/TikTokDownload#696]
**描述出现的错误**
使用配置文件与CLI下载抖音用户发布视频失败

---

**bug复现**
复现这次行为的步骤：
1.使用命令行对主配置文件app.yam进行了初始化，然后使用了auto-cookie命令在app.yaml中成功设置cookie
2.使用VScode对app.yaml中各项参数进行配置
3.使用命令 “f2 dy -M post -u https://https://www.douyin.com/user/MS4wLjABAAAAgskWetxAG0wYF78v2pBEIGHrjKa0aMHgflAj_H5f2k4?vid=7356588700924497164 -c conf/app.yaml

**命令运行结果**
INFO     App: douyin
INFO     主配置路径：D:\Douyindownloader\venv\Lib\site-packages\f2\conf\app.yaml
INFO     自定义配置路径：D:\Douyindownloader\venv\Lib\site-packages\f2\conf\app.yaml
INFO     Version 0.0.1.5

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "D:\Douyindownloader\venv\Scripts\f2.exe\__main__.py", line 7, in <module>
  File "D:\Douyindownloader\venv\Lib\site-packages\click\core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Douyindownloader\venv\Lib\site-packages\click\core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "D:\Douyindownloader\venv\Lib\site-packages\click\core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Douyindownloader\venv\Lib\site-packages\click\core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Douyindownloader\venv\Lib\site-packages\click\core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Douyindownloader\venv\Lib\site-packages\click\decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Douyindownloader\venv\Lib\site-packages\f2\apps\douyin\cli.py", line 443, in douyin
    ctx.invoke(set_cli_config, **kwargs)
  File "D:\Douyindownloader\venv\Lib\site-packages\click\core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Douyindownloader\venv\Lib\site-packages\click\decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Douyindownloader\venv\Lib\site-packages\f2\cli\cli_commands.py", line 135, in set_cli_config
    asyncio.run(run_app(kwargs))
  File "D:\Python\Python312\Lib\asyncio\runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "D:\Python\Python312\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Python\Python312\Lib\asyncio\base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "D:\Douyindownloader\venv\Lib\site-packages\f2\cli\cli_commands.py", line 144, in run_app
    await app_module.main(kwargs)
  File "D:\Douyindownloader\venv\Lib\site-packages\f2\apps\douyin\handler.py", line 1484, in main
    await mode_function_map[mode](DouyinHandler(kwargs))
  File "D:\Douyindownloader\venv\Lib\site-packages\f2\apps\douyin\handler.py", line 257, in handle_user_post
    user_path = await self.get_or_add_user_data(self.kwargs, sec_user_id, udb)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Douyindownloader\venv\Lib\site-packages\f2\apps\douyin\handler.py", line 151, in get_or_add_user_data
    await db.add_user_info(**current_user_data._to_dict())
  File "D:\Douyindownloader\venv\Lib\site-packages\f2\apps\douyin\db.py", line 74, in add_user_info
    await self.execute(
  File "D:\Douyindownloader\venv\Lib\site-packages\f2\db\base_db.py", line 55, in execute
    await cursor.execute(query, parameters)
  File "D:\Douyindownloader\venv\Lib\site-packages\aiosqlite\cursor.py", line 48, in execute
    await self._execute(self._cursor.execute, sql, parameters)
  File "D:\Douyindownloader\venv\Lib\site-packages\aiosqlite\cursor.py", line 40, in _execute
    return await self._conn._execute(fn, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Douyindownloader\venv\Lib\site-packages\aiosqlite\core.py", line 133, in _execute
    return await future
           ^^^^^^^^^^^^
  File "D:\Douyindownloader\venv\Lib\site-packages\aiosqlite\core.py", line 106, in run
    result = function()
             ^^^^^^^^^^
sqlite3.OperationalError: table user_info_web has no column named nickname_raw

**桌面：**
-操作系统：Windows11 64bit
-vpn代理：关闭
-项目版本：1.5.0.0
-py版本：3.12.3

**附文**
当相同操作步骤并使用自定义配置（其中填写了url未用CLI -u选项）时亦出现同样的提示，在Download文件夹中已新建文件，但文件下没有任何下载内容
(**配置文件中cookie已使用--auto-cookie配置，图中已略去**)
![image](https://github.com/Johnserf-Seed/TikTokDownload/assets/127164184/48a1e1e6-1766-4334-bd4b-87798a18d69c)

---

![image](https://github.com/Johnserf-Seed/TikTokDownload/assets/127164184/68b83934-0207-45d6-813f-2dd5145c45e1)

尝试过使用pip命令对f2进行卸载重装，但仍然未解决

**Comment by Johnserf-Seed** [comment]
升级前多留意readme
![image](https://github.com/Johnserf-Seed/TikTokDownload/assets/40727745/a3720516-499e-40ca-9051-eae6726245db)
