### ISSUE TITLE
[BUG]json.decoder.JSONDecodeError

### ISSUE THREAD

**Issue by boluohong** [Johnserf-Seed/TikTokDownload#699]
用的win7系统，所以只能用的旧版本13090
之前项目更新后，还能用就凑合用了
这两天不行了
报错如下

[   💻   ]:Windows平台
[  提示  ]:读取命令完成!
[  提示  ]:读取命令完成!
[  提示  ]:批量获取所有视频中!
[  提示  ]:用户的sec_id=MS4wLjABAAAA9NJQDiprYwXXT7qHvoXspF9DbLlCJ9er8vQZ5jM7okA
[  提示  ]:正在进行第 1 次尝试
[  用户  ]:朝阳刘亦肥
[  提示  ]:抓获用户主页数据成功!
[  提示  ]:正在替换当页所有作品非法字符，耐心等待!
[  提示  ]:正在替换作者非法字符，耐心等待!

[  提示  ]:正在对 1709377523000 页进行第 1 次尝试！
[  提示  ]:第 1702738945000 页抓获数据成功!
[  提示  ]:正在替换当页所有作品非法字符，耐心等待!
[  提示  ]:正在替换作者非法字符，耐心等待!
Traceback (most recent call last):
  File "1.py", line 32, in <module>
    profile.getProfile(cmd.setting())
  File "T:\0311\Util\Profile.py", line 132, in getProfile
    self.getData(self.api_post_url)
  File "T:\0311\Util\Profile.py", line 182, in getData
    self.getVideoInfo(result)
  File "T:\0311\Util\Profile.py", line 303, in getVideoInfo
    self.getNextData()
  File "T:\0311\Util\Profile.py", line 233, in getNextData
    self.getVideoInfo(result)
  File "T:\0311\Util\Profile.py", line 300, in getVideoInfo
    datas = Util.Images(self.headers).get_all_images(self.image_list)
  File "T:\0311\Util\Images.py", line 56, in get_all_images
    js = Util.json.loads(r)
  File "C:\Users\hp\AppData\Local\Programs\Python\Python37\lib\json\__init__.py"
, line 348, in loads
    return _default_decoder.decode(s)
  File "C:\Users\hp\AppData\Local\Programs\Python\Python37\lib\json\decoder.py",
 line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\hp\AppData\Local\Programs\Python\Python37\lib\json\decoder.py",
 line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by Johnserf-Seed** [comment]
旧版不维护了，请用新版
