### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by fungchunhoeasy** [Johnserf-Seed/TikTokDownload#706]
自动获取cookie
无论我用哪个浏览器打开 全部关闭或者打开单个抖音页面都显示这个 请问怎么解决
ERROR    请关闭所有已打开的浏览器重试，并且你有适当的权限访问浏览器！
Aborted!

**Comment by Johnserf-Seed** [comment]
去任务管理器检查是否真正退出了浏览器进程

**Comment by fungchunhoeasy** [comment]
是否要使用命令行的参数更新配置文件？`C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-packages\f2\conf\app.yaml` [Y/n]: y
配置文件已更新!
INFO     主配置路径：C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-packages\f2\conf\app.yaml
INFO     自定义配置路径：C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-packages\f2\conf\app.ya
         ml
ERROR    缺乏URL参数，详情看命令帮助

**Comment by fungchunhoeasy** [comment]
这算是成功了吗
然后
PS C:\Users\Administrator> f2 dy -u https://v.douyin.com/iYvDJbHH/
INFO     App: douyin
INFO     主配置路径：C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-packages\f2\conf\app.yaml
INFO     自定义配置路径：C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-packages\f2\conf\app.ya
         ml
INFO     Version 0.0.1.5
ERROR    不存在该模式: None
不知道哪里有问题

**Comment by Johnserf-Seed** [comment]
https://johnserf-seed.github.io/f2/site-config.html#%E5%88%9D%E5%A7%8B%E5%8C%96%E9%85%8D%E7%BD%AE%E6%96%87%E4%BB%B6

**Comment by JoeanAmier** [comment]
Edge 浏览器在关闭窗口后也会有进程，要在任务管理器关闭。

**Comment by fungchunhoeasy** [comment]
> https://johnserf-seed.github.io/f2/site-config.html#%E5%88%9D%E5%A7%8B%E5%8C%96%E9%85%8D%E7%BD%AE%E6%96%87%E4%BB%B6

我按照教程里生成一个文件在C:\Users\Administrator 那我现在是设置这个还是设置C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-packages\f2\conf这里面的？
小白看不太懂那个教程的低频和什么的术语 麻烦指教了

**Comment by Johnserf-Seed** [comment]
1. `个人配置`>`本地配置`
2. 将低频率修改的配置放`本地配置`，将`mode`或`url`等会高频修改的参数放`个人配置`
3. 可以创建多个`个人配置`来设置不同`用户的主页`与`模式`，只需在命令行切换`-c`的参数就可以灵活下载不同配置文件从而减少`cookie`等参数的复制

**Comment by Johnserf-Seed** [comment]
https://johnserf-seed.github.io/f2/site-config.html#%E8%87%AA%E5%AE%9A%E4%B9%89%E9%85%8D%E7%BD%AE%E6%96%87%E4%BB%B6

**Comment by fungchunhoeasy** [comment]
cover: null
  desc: null
  folderize: null
  interval: all
  languages: null
  lyric: null
  max_connections: 5
  max_counts: 0
  max_retries: 5
  max_tasks: 10
  mode: post
  music: null
  naming: {create}_{desc}
  page_counts: 20
  path: F:\xxz
  timeout: 10
  url: null

出现以下错误
PS C:\Users\Administrator> f2 dy -c C:\Users\Administrator\app.yaml -u https://www.douyin.com/user/MS4wLjABAAAAehyF8dX5pMerC2dUMR4Hu8YC5MLar9C01EnbyFCc8JZrBOxWqEAe6VP8rzqupgTK?vid=7356915618664156456
INFO     App: douyin
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Scripts\f2.exe\__main__.py", line 7, in <module>
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-packages\click\core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-packages\click\core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-packages\click\core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-packages\click\core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-packages\click\core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-packages\click\decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-packages\f2\apps\douyin\cli.py", line 409, in douyin
    custom_manager = ConfigManager(config)
                     ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-packages\f2\utils\conf_manager.py", line 24, in __init__
    self.config = self.load_config()
                  ^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-packages\f2\utils\conf_manager.py", line 32, in load_config
    return yaml.safe_load(self.filepath.read_text(encoding="utf-8")) or {}
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-packages\yaml\__init__.py", line 125, in safe_load
    return load(stream, SafeLoader)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-packages\yaml\__init__.py", line 81, in load
    return loader.get_single_data()
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-packages\yaml\constructor.py", line 49, in get_single_data
    node = self.get_single_node()
           ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-packages\yaml\composer.py", line 36, in get_single_node
    document = self.compose_document()
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-packages\yaml\composer.py", line 55, in compose_document
    node = self.compose_node(None, None)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-packages\yaml\composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-packages\yaml\composer.py", line 133, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-packages\yaml\composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-packages\yaml\composer.py", line 127, in compose_mapping_node
    while not self.check_event(MappingEndEvent):
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-packages\yaml\parser.py", line 98, in check_event
    self.current_event = self.state()
                         ^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-packages\yaml\parser.py", line 438, in parse_block_mapping_key
    raise ParserError("while parsing a block mapping", self.marks[-1],
yaml.parser.ParserError: while parsing a block mapping
  in "<unicode string>", line 2, column 3:
      cookie: ttwid=1%7CQcE4NyJJf8WEMx ...
      ^
expected <block end>, but found '<scalar>'
  in "<unicode string>", line 15, column 19:
      naming: {create}_{desc}

**Comment by Johnserf-Seed** [comment]
百度yaml格式

**Comment by Johnserf-Seed** [comment]
![image](https://github.com/Johnserf-Seed/TikTokDownload/assets/40727745/c8b04c0f-fdbc-4421-ad12-b353cfeab161)

**Comment by fungchunhoeasy** [comment]
可以了！！！！！！！ 感谢 ！！！！！！

**Comment by fungchunhoeasy** [comment]
还有最后一个问题 我下载tk 代理填写在conf.yaml的文件夹显示一串错误 然后直接用-P指令提示Error: Option '-P' requires 2 arguments. 
我是用r2rayN的 端口是10808 我填写http://127.0.0.1:10808 好像不行 系统代理是10809
PS C:\Users\Administrator> f2 tk -c C:\Users\Administrator\tk.yaml -u https://www.tiktok.com/@yul__1222 -P http://127.0.0.1:10808 https://127.0.0.1:10810
INFO     App: tiktok
INFO     主配置路径：C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-packages\f2\conf\app.yaml
INFO     自定义配置路径：C:\Users\Administrator\tk.yaml
INFO     Version 0.0.1.5
请前往QA文档 https://johnserf-seed.github.io/f2/question-answer/qa.html 查看相关帮助
ERROR    请求端点失败，请检查当前网络环境。
         链接：https://mssdk-sg.tiktok.com/web/common?msToken=1Ab-7YxR9lUHSem0PraI_XzdKmpHb6j50L8AaXLAd2aWTdoJCYLfX_67rV
         QFE4UwwHVHmyG_NfIipqrlLT3kCXps-5PYlNAqtdwEg7TrDyTAfCKyBrOLmhMUjB55oW8SPZ4_EkNxNFUdV7MquA==，代理：{'http://':
         None, 'https://': None}，异常类名：TokenManager，异常详细信息：timed out

**Comment by suka9308** [comment]
你好，作者。小白运行的时候遇到一个问题，找了半天也没找到类似的问题。
(venv) PS D:\Chengxu\TikTokDownload-main> f2 dy -u https://v.douyin.com/iYTLRvBp/
INFO     App: douyin
INFO     主配置路径：D:\Chengxu\TikTokDownload-main\venv\Lib\site-packages\f2\conf\app.yaml
INFO     自定义配置路径：D:\Chengxu\TikTokDownload-main\venv\Lib\site-packages\f2\conf\app.yaml
INFO     Version 0.0.1.5
INFO     开始爬取作品：7359192648004996392
WARNING  没有找到符合条件的作品

DEBUG提示  ERROR    缺乏URL参数，详情看命令帮助

**Comment by Johnserf-Seed** [comment]
> 你好，作者。小白运行的时候遇到一个问题，找了半天也没找到类似的问题。 (venv) PS D:\Chengxu\TikTokDownload-main> f2 dy -u https://v.douyin.com/iYTLRvBp/ INFO App: douyin INFO 主配置路径：D:\Chengxu\TikTokDownload-main\venv\Lib\site-packages\f2\conf\app.yaml INFO 自定义配置路径：D:\Chengxu\TikTokDownload-main\venv\Lib\site-packages\f2\conf\app.yaml INFO Version 0.0.1.5 INFO 开始爬取作品：7359192648004996392 WARNING 没有找到符合条件的作品
> 
> DEBUG提示 ERROR 缺乏URL参数，详情看命令帮助

https://johnserf-seed.github.io/f2/question-answer/qa.html#warning-%E6%B2%A1%E6%9C%89%E6%89%BE%E5%88%B0%E7%AC%A6%E5%90%88%E6%9D%A1%E4%BB%B6%E7%9A%84%E4%BD%9C%E5%93%81

**Comment by Johnserf-Seed** [comment]
> 还有最后一个问题 我下载tk 代理填写在conf.yaml的文件夹显示一串错误 然后直接用-P指令提示Error: Option '-P' requires 2 arguments. 我是用r2rayN的 端口是10808 我填写http://127.0.0.1:10808 好像不行 系统代理是10809 PS C:\Users\Administrator> f2 tk -c C:\Users\Administrator\tk.yaml -u https://www.tiktok.com/@yul__1222 -P http://127.0.0.1:10808 https://127.0.0.1:10810 INFO App: tiktok INFO 主配置路径：C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-packages\f2\conf\app.yaml INFO 自定义配置路径：C:\Users\Administrator\tk.yaml INFO Version 0.0.1.5 请前往QA文档 https://johnserf-seed.github.io/f2/question-answer/qa.html 查看相关帮助 ERROR 请求端点失败，请检查当前网络环境。 链接：https://mssdk-sg.tiktok.com/web/common?msToken=1Ab-7YxR9lUHSem0PraI_XzdKmpHb6j50L8AaXLAd2aWTdoJCYLfX_67rV QFE4UwwHVHmyG_NfIipqrlLT3kCXps-5PYlNAqtdwEg7TrDyTAfCKyBrOLmhMUjB55oW8SPZ4_EkNxNFUdV7MquA==，代理：{'http://': None, 'https://': None}，异常类名：TokenManager，异常详细信息：timed out

你应该使用这样的命令，代理的`https`配置在低版本的`urllib3`库中是不支持的这和`python`版本有关，所以只能都设为`http`
![image](https://github.com/Johnserf-Seed/TikTokDownload/assets/40727745/a26fb8f3-8af8-4ad1-8f12-6eabd9e24198)

而出现代理不可用的情况就是你本地代理的设置了，需参考操作系统设置中的代理服务器来填
![image](https://github.com/Johnserf-Seed/TikTokDownload/assets/40727745/0ea08dae-dbc9-4b22-a940-6bc88f5ef2a8)

希望可以解决你遇到的问题
