### ISSUE TITLE
请问这是什么意思

### ISSUE THREAD

**Issue by huiyichenjiyi** [Johnserf-Seed/TikTokDownload#720]
C:\Users\huiyichenjiyi>pip show f2
Name: f2
Version: 0.0.1.5
Summary: 🚀Asynchronous based full-platform download tool
Home-page:
Author:
Author-email: Johnserf-Seed <johnserf-seed@foxmail.com>
License:
Location: C:\Users\huiyichenjiyi\AppData\Roaming\Python\Python312\site-packages
Requires: aiofiles, aiosqlite, browser-cookie3, click, httpx, importlib-resources, jsonpath-ng, m3u8, pydantic, pytest, pytest-asyncio, pyyaml, qrcode, rich
Required-by:

C:\Users\huiyichenjiyi>f2 dy -c C:\Users\huiyichenjiyi\AppData\Roaming\Python\Python312\site-packages\f2\conf\1.yaml
INFO     App: douyin
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\huiyichenjiyi\AppData\Roaming\Python\Python312\Scripts\f2.exe\__main__.py", line 7, in <module>
  File "C:\Users\huiyichenjiyi\AppData\Roaming\Python\Python312\site-packages\click\core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\huiyichenjiyi\AppData\Roaming\Python\Python312\site-packages\click\core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "C:\Users\huiyichenjiyi\AppData\Roaming\Python\Python312\site-packages\click\core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\huiyichenjiyi\AppData\Roaming\Python\Python312\site-packages\click\core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\huiyichenjiyi\AppData\Roaming\Python\Python312\site-packages\click\core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\huiyichenjiyi\AppData\Roaming\Python\Python312\site-packages\click\decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\huiyichenjiyi\AppData\Roaming\Python\Python312\site-packages\f2\apps\douyin\cli.py", line 374, in douyin
    main_manager = ConfigManager(f2.APP_CONFIG_FILE_PATH)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\huiyichenjiyi\AppData\Roaming\Python\Python312\site-packages\f2\utils\conf_manager.py", line 24, in __init__
    self.config = self.load_config()
                  ^^^^^^^^^^^^^^^^^^
  File "C:\Users\huiyichenjiyi\AppData\Roaming\Python\Python312\site-packages\f2\utils\conf_manager.py", line 32, in load_config
    return yaml.safe_load(self.filepath.read_text(encoding="utf-8")) or {}
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\huiyichenjiyi\AppData\Roaming\Python\Python312\site-packages\yaml\__init__.py", line 125, in safe_load
    return load(stream, SafeLoader)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\huiyichenjiyi\AppData\Roaming\Python\Python312\site-packages\yaml\__init__.py", line 81, in load
    return loader.get_single_data()
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\huiyichenjiyi\AppData\Roaming\Python\Python312\site-packages\yaml\constructor.py", line 49, in get_single_data
    node = self.get_single_node()
           ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\huiyichenjiyi\AppData\Roaming\Python\Python312\site-packages\yaml\composer.py", line 36, in get_single_node
    document = self.compose_document()
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\huiyichenjiyi\AppData\Roaming\Python\Python312\site-packages\yaml\composer.py", line 55, in compose_document
    node = self.compose_node(None, None)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\huiyichenjiyi\AppData\Roaming\Python\Python312\site-packages\yaml\composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\huiyichenjiyi\AppData\Roaming\Python\Python312\site-packages\yaml\composer.py", line 127, in compose_mapping_node
    while not self.check_event(MappingEndEvent):
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\huiyichenjiyi\AppData\Roaming\Python\Python312\site-packages\yaml\parser.py", line 98, in check_event
    self.current_event = self.state()
                         ^^^^^^^^^^^^
  File "C:\Users\huiyichenjiyi\AppData\Roaming\Python\Python312\site-packages\yaml\parser.py", line 428, in parse_block_mapping_key
    if self.check_token(KeyToken):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\huiyichenjiyi\AppData\Roaming\Python\Python312\site-packages\yaml\scanner.py", line 116, in check_token
    self.fetch_more_tokens()
  File "C:\Users\huiyichenjiyi\AppData\Roaming\Python\Python312\site-packages\yaml\scanner.py", line 223, in fetch_more_tokens
    return self.fetch_value()
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\huiyichenjiyi\AppData\Roaming\Python\Python312\site-packages\yaml\scanner.py", line 577, in fetch_value
    raise ScannerError(None, None,
yaml.scanner.ScannerError: mapping values are not allowed here
  in "<unicode string>", line 4, column 9:
      naming: '{create}_{desc}'

**Comment by Johnserf-Seed** [comment]
请按issue模板填写，否则视为无效issue，yml格式问题可以百度不要直接提issue
