### ISSUE TITLE
[BUG]突然报错了

### ISSUE THREAD

**Issue by zhiben5201** [Johnserf-Seed/TikTokDownload#736]
Traceback (most recent call last):
  File "C:\Users\15920\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\15920\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "F:\douyin4\venv\Scripts\f2.exe\__main__.py", line 7, in <module>
    sys.exit(main())
  File "F:\douyin4\venv\lib\site-packages\click\core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "F:\douyin4\venv\lib\site-packages\click\core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "F:\douyin4\venv\lib\site-packages\click\core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "F:\douyin4\venv\lib\site-packages\click\core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "F:\douyin4\venv\lib\site-packages\click\core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "F:\douyin4\venv\lib\site-packages\click\decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "F:\douyin4\venv\lib\site-packages\f2\apps\douyin\cli.py", line 443, in douyin
    ctx.invoke(set_cli_config, **kwargs)
  File "F:\douyin4\venv\lib\site-packages\click\core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "F:\douyin4\venv\lib\site-packages\click\decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "F:\douyin4\venv\lib\site-packages\f2\cli\cli_commands.py", line 135, in set_cli_config
    asyncio.run(run_app(kwargs))
  File "C:\Users\15920\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\15920\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 649, in run_until_complete
    return future.result()
  File "F:\douyin4\venv\lib\site-packages\f2\cli\cli_commands.py", line 144, in run_app
    await app_module.main(kwargs)
  File "F:\douyin4\venv\lib\site-packages\f2\apps\douyin\handler.py", line 1484, in main
    await mode_function_map[mode](DouyinHandler(kwargs))
  File "F:\douyin4\venv\lib\site-packages\f2\apps\douyin\handler.py", line 264, in handle_user_post
    self.kwargs, aweme_data_list._to_list(), user_path
  File "F:\douyin4\venv\lib\site-packages\f2\apps\douyin\filter.py", line 345, in _to_list
    attr_values = getattr(self, key)
  File "F:\douyin4\venv\lib\site-packages\f2\apps\douyin\filter.py", line 243, in video_bit_rate
    return [
  File "F:\douyin4\venv\lib\site-packages\f2\apps\douyin\filter.py", line 249, in <listcomp>
    if len(aweme) == 1
TypeError: object of type 'NoneType' has no len()
请按任意键继续. . .
今天基本没用过，所以不存在多次使用后的超限，更新了COOKIE也没用

**Comment by guanyuz1** [comment]
我也是我还重新装了一下，有的博主正常，有几个就报这个错误，也不知道是什么原因

**Comment by Johnserf-Seed** [comment]
https://github.com/Johnserf-Seed/f2/issues/104

**Comment by Johnserf-Seed** [comment]
`0.0.1.6-pw2`已发布，使用新版即可。

https://johnserf-seed.github.io/f2/guide/apps/douyin/cli.html

**Comment by zhiben5201** [comment]
> `0.0.1.6-pw2`已发布，使用新版即可。
> 
> https://johnserf-seed.github.io/f2/guide/apps/douyin/cli.html

非常感谢

**Comment by zsmlgy** [comment]
> `0.0.1.6-pw2`已发布，使用新版即可。
> 
> https://johnserf-seed.github.io/f2/guide/apps/douyin/cli.html

现在又出现这个问题了，用的是最新版本
